import type { AgentToolDefinition } from "../agent-contracts"

export const MVP_AGENT_TOOL_DEFINITIONS = [
  {
    key: "readTenantOperatingSnapshot",
    description: "Read the tenant operating snapshot through the snapshot service.",
    ownerService: "services/snapshots",
    moduleSlug: "dashboard",
    requiredPermission: "dashboard.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:tenant-operating-snapshot-input:v1",
    outputSchemaHash: "agent-schema:tenant-operating-snapshot-output:v1",
    evidenceBehavior: "Preserve source hash, evidence grade, freshness, blockers, and redactions.",
  },
  {
    key: "readBusinessSignals",
    description: "Read permission-filtered business signals derived from trusted snapshots.",
    ownerService: "services/signals",
    moduleSlug: "dashboard",
    requiredPermission: "dashboard.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:business-signals-input:v1",
    outputSchemaHash: "agent-schema:business-signals-output:v1",
    evidenceBehavior: "Preserve each signal's permission, evidence grade, blockers, and redactions.",
  },
  {
    key: "readActionQueue",
    description: "Read the action queue without assignment, resolution, or dismissal authority.",
    ownerService: "services/signals",
    moduleSlug: "dashboard",
    requiredPermission: "dashboard.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:action-queue-input:v1",
    outputSchemaHash: "agent-schema:action-queue-output:v1",
    evidenceBehavior: "Return permission-filtered summaries and existing evidence metadata only.",
  },
  {
    key: "readProofTrail",
    description: "Read a proof trail for an authorized subject.",
    ownerService: "services/evidence",
    moduleSlug: "reports",
    requiredPermission: "reports.audit.view",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:proof-trail-input:v1",
    outputSchemaHash: "agent-schema:proof-trail-output:v1",
    evidenceBehavior: "Preserve proof subject, nodes, edges, blockers, redactions, and availability.",
  },
  {
    key: "readPaymentTruthSnapshot",
    description: "Read the payment truth snapshot.",
    ownerService: "services/snapshots",
    moduleSlug: "payment_reconciliation",
    requiredPermission: "payments.reconciliation.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:payment-truth-input:v1",
    outputSchemaHash: "agent-schema:payment-truth-output:v1",
    evidenceBehavior: "Preserve payment evidence grade, source hash, freshness, blockers, and redactions.",
  },
  {
    key: "readPaymentReconciliationWorkbench",
    description: "Read the payment reconciliation workbench without match or posting authority.",
    ownerService: "services/payments",
    moduleSlug: "payment_reconciliation",
    requiredPermission: "payments.reconciliation.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:payment-workbench-input:v1",
    outputSchemaHash: "agent-schema:payment-workbench-output:v1",
    evidenceBehavior: "Require payment evidence and apply provider-reference and suspense redaction.",
  },
  {
    key: "readInventoryCashSnapshot",
    description: "Read the inventory cash snapshot.",
    ownerService: "services/snapshots",
    moduleSlug: "inventory",
    requiredPermission: "inventory.levels.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:inventory-cash-input:v1",
    outputSchemaHash: "agent-schema:inventory-cash-output:v1",
    evidenceBehavior: "Preserve stock source hash, freshness, negative-stock blockers, and redactions.",
  },
  {
    key: "readCloseReadinessSnapshot",
    description: "Read close readiness without certification or period-close authority.",
    ownerService: "services/snapshots",
    moduleSlug: "close_assurance",
    requiredPermission: "accounting.close.read",
    riskLevel: "read_only",
    toolType: "read_only",
    inputSchemaHash: "agent-schema:close-readiness-input:v1",
    outputSchemaHash: "agent-schema:close-readiness-output:v1",
    evidenceBehavior: "Preserve close evidence grade, freshness, findings, blockers, and redactions.",
  },
] as const satisfies readonly AgentToolDefinition[]

