ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_RECEIVABLE_DOCUMENT';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_STATEMENT_SNAPSHOT';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_STATEMENT';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_STATEMENT_DELIVERY';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_STATEMENT_RECIPIENT_ACTION';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_SETTLEMENT_ALLOCATION';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'CUSTOMER_SETTLEMENT_REVERSAL';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'ACCOUNTANT_CLIENT_INVITE';
