// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[locale]/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/login-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login-v2">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/login-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/register-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/register-v2">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/register-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/register">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reset-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/unauthorized">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/user-invite/[organisationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/user-invite/[organisationId]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/user-invite/[organisationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(auth)/verify/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/verify/[userId]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/verify/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/accountant-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/accountant-access">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/accountant-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/accountant-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/accountant-portal">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/accountant-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/accountant-portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/accountant-portfolio">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/accountant-portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/accounts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/close/[periodId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/close/[periodId]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/close/[periodId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/close/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/close">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/close/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/control-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/control-center">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/control-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/journals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/journals/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/journals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/journals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/journals">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/journals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/reports/financial-statements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/reports/financial-statements">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/reports/financial-statements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/reports/trial-balance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/reports/trial-balance">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/reports/trial-balance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/accounting/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/accounting/setup">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/accounting/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/analytics/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/analytics/referrals">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/analytics/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/analytics/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/analytics/reports">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/analytics/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/assurance/control-tower/incidents/[incidentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/assurance/control-tower/incidents/[incidentId]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/assurance/control-tower/incidents/[incidentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/assurance/control-tower/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/assurance/control-tower">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/assurance/control-tower/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/cashDrawer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/cashDrawer">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/cashDrawer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/change-password">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/compliance">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/[id]/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers/[id]/orders">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/[id]/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/[id]/statement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers/[id]/statement">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/[id]/statement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/daily-digest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/daily-digest">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/daily-digest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/analytics">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/cash-command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/cash-command">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/cash-command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/cash-drawer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/cash-drawer">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/cash-drawer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/cash-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/cash-flow">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/cash-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/cash-payment-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/cash-payment-history">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/cash-payment-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/costs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/costs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/costs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/payables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/payables">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/payables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/payments">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/profit-loss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/profit-loss">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/profit-loss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/profitability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/profitability">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/profitability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/receivables/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/receivables/history">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/receivables/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/receivables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/receivables">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/receivables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/reconciliation">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/retail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/retail">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/retail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/sales">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/stock-to-cash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/stock-to-cash">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/stock-to-cash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/finance/tax-rates/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/finance/tax-rates/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/finance/tax-rates/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/brands/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/brands/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/brands/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/brands/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/brands/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/brands/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/brands">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/categories/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/categories/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/categories/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/categories">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/others/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items/[id]/others">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/others/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items/[id]/suppliers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/[id]/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/items">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/loss-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/loss-control">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/loss-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/movements">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/units/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/units/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/units/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/units/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/units/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/units/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/units/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/inventory/units">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/units/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/items/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/items/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/items/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/items">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/manager-action-center/daily-close/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/manager-action-center/daily-close">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/manager-action-center/daily-close/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/manager-action-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/manager-action-center">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/manager-action-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/notifications-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/notifications-demo">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/notifications-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/owner-war-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/owner-war-room">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/owner-war-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/attendance">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/compensation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/compensation">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/compensation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/contracts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/declarations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/declarations">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/declarations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/employees">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/payments">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/payslips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/payslips">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/payslips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/register">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/runs">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/payroll/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/payroll/setup">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/payroll/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/[employeeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people/[employeeId]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/[employeeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people/approvals">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people/history">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people/me">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/people/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/people/team">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/people/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/pos">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchase-orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchase-orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchase-orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchase-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchase-orders/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchase-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/payables/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/payables/history">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/payables/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/payables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/payables">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/payables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/suppliers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/suppliers/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/purchases/suppliers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/sales">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/appearance">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/company">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/locations/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/locations/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/locations/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/locations/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/locations/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/locations/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/locations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/locations/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/locations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/locations">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/modules">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/notifications">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/organization">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/roles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/roles/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/roles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/roles">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/roles/update/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/roles/update/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/roles/update/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/security">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/tax-rates/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/tax-rates/create">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/tax-rates">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/terminals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/terminals">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/terminals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/settings/users">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/suppliersSystem/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/suppliersSystem/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/suppliersSystem/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/suppliersSystem/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/suppliersSystem/[id]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/suppliersSystem/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/suppliersSystem/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/suppliersSystem/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/suppliersSystem/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/suppliersSystem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/suppliersSystem">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/suppliersSystem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(home)/landing-preview/founder-journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/landing-preview/founder-journey">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(home)/landing-preview/founder-journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(home)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(home)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(home)/waitlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/waitlist">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(home)/waitlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(home)/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/workflows">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(home)/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/ohada-os/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ohada-os">> = Specific
  const handler = {} as typeof import("../../app/[locale]/ohada-os/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/update/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/update">> = Specific
  const handler = {} as typeof import("../../app/[locale]/update/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer-statement/[statementId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-statement/[statementId]">> = Specific
  const handler = {} as typeof import("../../app/customer-statement/[statementId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/.well-known/security.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/security.txt">> = Specific
  const handler = {} as typeof import("../../app/.well-known/security.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customer-statements/[statementId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-statements/[statementId]/actions">> = Specific
  const handler = {} as typeof import("../../app/api/customer-statements/[statementId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/customer-statements/[statementId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-statements/[statementId]">> = Specific
  const handler = {} as typeof import("../../app/api/customer-statements/[statementId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/internal/agents/reconcile-abandoned/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/agents/reconcile-abandoned">> = Specific
  const handler = {} as typeof import("../../app/api/internal/agents/reconcile-abandoned/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/permissions">> = Specific
  const handler = {} as typeof import("../../app/api/me/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/receipts/[receiptId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receipts/[receiptId]">> = Specific
  const handler = {} as typeof import("../../app/api/receipts/[receiptId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/referrals/[referralCode]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals/[referralCode]">> = Specific
  const handler = {} as typeof import("../../app/api/referrals/[referralCode]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/security-txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-txt">> = Specific
  const handler = {} as typeof import("../../app/api/security-txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploadthing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploadthing">> = Specific
  const handler = {} as typeof import("../../app/api/uploadthing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/organisations/[id]/briefItems/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/organisations/[id]/briefItems">> = Specific
  const handler = {} as typeof import("../../app/api/v1/organisations/[id]/briefItems/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/organisations/[id]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/organisations/[id]/items">> = Specific
  const handler = {} as typeof import("../../app/api/v1/organisations/[id]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/organisations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/organisations">> = Specific
  const handler = {} as typeof import("../../app/api/v1/organisations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[locale]/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/customers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/customers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/brands/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/inventory/brands">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/brands/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/categories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/inventory/categories">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/categories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/inventory/units/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/inventory/units">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/inventory/units/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/purchases/suppliers">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/purchases/suppliers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/locations/new/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/settings/locations/new">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/locations/new/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/roles/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/settings/roles">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/roles/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/settings/tax-rates">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/tax-rates/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(dashboard)/dashboard/settings/users/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/settings/users">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(dashboard)/dashboard/settings/users/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/(home)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/(home)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
