export const inventoryLossWorkbenchCopy = {
  en: {
    eyebrow: "Inventory control",
    title: "Inventory Loss Control",
    summary:
      "Review completed loss-bearing stock adjustments, their recorded value, operating scope, and available evidence.",
    loading: "Loading source",
    refreshing: "Refreshing",
    complete: "Complete source",
    partial: "Partial source",
    refresh: "Refresh",
    filtersTitle: "Reporting period",
    filtersDetail:
      "The end date is inclusive. Periods are limited to 366 days.",
    from: "From",
    through: "Through",
    reset: "Reset period",
    invalidPeriod: "Invalid reporting period",
    lossValue: "Recorded loss value",
    lossValueDetail: "Value recorded on completed loss lines",
    lossLines: "Loss lines",
    lossLinesDetail: "Completed negative adjustment lines",
    adjustments: "Adjustments",
    adjustmentsDetail: "Distinct completed source adjustments",
    evidenceCoverage: "Evidence coverage",
    evidenceCoverageDetail: "Lines with an evidence or document hash",
    coverageTitle: "Trust coverage",
    coverageDetail:
      "Coverage is calculated by the service from the source lines in this snapshot.",
    evidence: "Evidence",
    valuation: "Valuation",
    approval: "Approval attribution",
    source: "Source completeness",
    tenantScope: "Tenant-wide authorized scope",
    managedScope: "managed locations authorized",
    scope: "Operating scope",
    timezone: "Organization timezone",
    period: "Period",
    generated: "Generated",
    emptyTitle: "No recorded inventory loss",
    emptyMessage:
      "No completed loss-bearing stock adjustment was found in this authorized scope and period.",
    errorTitle: "Inventory loss view could not load",
    retry: "Retry",
    permissionTitle: "Inventory loss access is unavailable",
    permissionMessage:
      "This account no longer has the server-side authority required for this inventory view.",
    sessionTitle: "Refresh the dashboard session",
    sessionMessage:
      "The current session cannot load trusted inventory loss evidence.",
    partialTitle: "Totals are partial",
    refreshFailedTitle: "The latest refresh failed",
    refreshFailedMessage:
      "Previously loaded evidence remains visible. Retry before relying on it as current.",
    breakdownTitle: "Loss breakdown",
    breakdownDetail:
      "Compare the same service-owned loss total across operational dimensions.",
    products: "Products",
    locations: "Locations",
    categories: "Categories",
    approvers: "Approvals",
    months: "Months",
    product: "Product",
    location: "Location",
    category: "Category",
    approver: "Approving actor",
    month: "Month",
    lines: "Lines",
    sourceAdjustments: "Adjustments",
    quantity: "Quantity lost",
    value: "Loss value",
    approvalMeaning:
      "The named actor approved the recorded adjustment. Approval does not establish who or what caused the loss.",
    recentTitle: "Recent source records",
    recentDetail:
      "The newest completed loss lines returned by the protected read model.",
    occurred: "Occurred",
    item: "Item",
    proof: "Proof",
    details: "Details",
    openDetails: "Open loss record details",
    recorded: "Recorded",
    unavailable: "Unavailable",
    drawerTitle: "Loss record",
    sourceIdentity: "Source identity",
    adjustmentNumber: "Adjustment number",
    adjustmentType: "Adjustment type",
    reason: "Recorded reason",
    countSession: "Count session",
    businessValue: "Business value",
    unitCost: "Unit cost",
    approvedBy: "Approved by",
    noApprover: "No approving actor recorded",
    evidenceState: "Evidence state",
    attributionGuard: "Attribution guard",
    none: "None",
    countVariance: "Count variance",
    damaged: "Damaged stock",
    expired: "Expired stock",
    recordedTheft: "Recorded theft adjustment",
    writeOff: "Write-off",
  },
  fr: {
    eyebrow: "Controle des stocks",
    title: "Controle Des Pertes De Stock",
    summary:
      "Examinez les ajustements de perte termines, leur valeur enregistree, le perimetre operationnel et les preuves disponibles.",
    loading: "Chargement de la source",
    refreshing: "Actualisation",
    complete: "Source complete",
    partial: "Source partielle",
    refresh: "Actualiser",
    filtersTitle: "Periode de rapport",
    filtersDetail:
      "La date de fin est incluse. La periode est limitee a 366 jours.",
    from: "Du",
    through: "Au",
    reset: "Reinitialiser",
    invalidPeriod: "Periode de rapport invalide",
    lossValue: "Valeur de perte enregistree",
    lossValueDetail: "Valeur des lignes de perte terminees",
    lossLines: "Lignes de perte",
    lossLinesDetail: "Lignes negatives d'ajustement terminees",
    adjustments: "Ajustements",
    adjustmentsDetail: "Ajustements sources distincts et termines",
    evidenceCoverage: "Couverture des preuves",
    evidenceCoverageDetail: "Lignes avec preuve ou empreinte de document",
    coverageTitle: "Couverture de confiance",
    coverageDetail:
      "La couverture est calculee par le service depuis les lignes sources de cet instantane.",
    evidence: "Preuves",
    valuation: "Valorisation",
    approval: "Attribution d'approbation",
    source: "Completude de la source",
    tenantScope: "Perimetre autorise de toute l'entreprise",
    managedScope: "sites geres autorises",
    scope: "Perimetre operationnel",
    timezone: "Fuseau de l'entreprise",
    period: "Periode",
    generated: "Genere",
    emptyTitle: "Aucune perte de stock enregistree",
    emptyMessage:
      "Aucun ajustement de perte termine n'a ete trouve dans ce perimetre et cette periode.",
    errorTitle: "La vue des pertes n'a pas pu etre chargee",
    retry: "Reessayer",
    permissionTitle: "Acces aux pertes indisponible",
    permissionMessage:
      "Ce compte ne dispose plus de l'autorite serveur requise pour cette vue.",
    sessionTitle: "Actualisez la session du tableau de bord",
    sessionMessage:
      "La session actuelle ne peut pas charger les preuves fiables de perte.",
    partialTitle: "Les totaux sont partiels",
    refreshFailedTitle: "La derniere actualisation a echoue",
    refreshFailedMessage:
      "Les preuves precedentes restent visibles. Reessayez avant de les considerer actuelles.",
    breakdownTitle: "Ventilation des pertes",
    breakdownDetail:
      "Comparez le meme total de perte gere par le service selon les dimensions operationnelles.",
    products: "Produits",
    locations: "Sites",
    categories: "Categories",
    approvers: "Approbations",
    months: "Mois",
    product: "Produit",
    location: "Site",
    category: "Categorie",
    approver: "Acteur approbateur",
    month: "Mois",
    lines: "Lignes",
    sourceAdjustments: "Ajustements",
    quantity: "Quantite perdue",
    value: "Valeur de perte",
    approvalMeaning:
      "L'acteur nomme a approuve l'ajustement enregistre. Cette approbation n'etablit pas la cause de la perte.",
    recentTitle: "Enregistrements sources recents",
    recentDetail:
      "Les lignes de perte terminees les plus recentes renvoyees par le modele protege.",
    occurred: "Date",
    item: "Article",
    proof: "Preuve",
    details: "Details",
    openDetails: "Ouvrir le detail de la perte",
    recorded: "Enregistree",
    unavailable: "Indisponible",
    drawerTitle: "Enregistrement de perte",
    sourceIdentity: "Identite de la source",
    adjustmentNumber: "Numero d'ajustement",
    adjustmentType: "Type d'ajustement",
    reason: "Motif enregistre",
    countSession: "Session de comptage",
    businessValue: "Valeur operationnelle",
    unitCost: "Cout unitaire",
    approvedBy: "Approuve par",
    noApprover: "Aucun acteur approbateur enregistre",
    evidenceState: "Etat de preuve",
    attributionGuard: "Garde d'attribution",
    none: "Aucun",
    countVariance: "Ecart de comptage",
    damaged: "Stock endommage",
    expired: "Stock expire",
    recordedTheft: "Ajustement de vol enregistre",
    writeOff: "Mise au rebut",
  },
} as const

export type InventoryLossWorkbenchCopy =
  {
    [Key in keyof (typeof inventoryLossWorkbenchCopy)["en"]]: string
  }
