import {
  hasAllRbacPermissions,
  hasAnyRbacPermission,
  hasRbacPermission,
} from "./security/rbac-permissions";

// Permission system for StockFlow - Comprehensive RBAC
export const PERMISSIONS = {
  // Organization Management
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  VIEW_ORGANIZATION_SETTINGS: 'VIEW_ORGANIZATION_SETTINGS',

  // User Management
  CREATE_USERS: 'CREATE_USERS',
  READ_USERS: 'READ_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
  DEACTIVATE_USERS: 'DEACTIVATE_USERS',

  // Role Management
  CREATE_ROLES: 'CREATE_ROLES',
  READ_ROLES: 'READ_ROLES',
  UPDATE_ROLES: 'UPDATE_ROLES',
  DELETE_ROLES: 'DELETE_ROLES',
  ASSIGN_ROLES: 'ASSIGN_ROLES',

  // Location Management
  CREATE_LOCATIONS: 'CREATE_LOCATIONS',
  READ_LOCATIONS: 'READ_LOCATIONS',
  UPDATE_LOCATIONS: 'UPDATE_LOCATIONS',
  DELETE_LOCATIONS: 'DELETE_LOCATIONS',
  MANAGE_LOCATION_SETTINGS: 'MANAGE_LOCATION_SETTINGS',

  // Inventory Management
  CREATE_ITEMS: 'CREATE_ITEMS',
  READ_ITEMS: 'READ_ITEMS',
  UPDATE_ITEMS: 'UPDATE_ITEMS',
  DELETE_ITEMS: 'DELETE_ITEMS',
  MANAGE_INVENTORY_LEVELS: 'MANAGE_INVENTORY_LEVELS',
  VIEW_INVENTORY_REPORTS: 'VIEW_INVENTORY_REPORTS',

  // Category Management
  CREATE_CATEGORIES: 'CREATE_CATEGORIES',
  READ_CATEGORIES: 'READ_CATEGORIES',
  UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
  DELETE_CATEGORIES: 'DELETE_CATEGORIES',

  // Brand Management
  CREATE_BRANDS: 'CREATE_BRANDS',
  BRANDS_READ: 'BRANDS_READ',
  UPDATE_BRANDS: 'UPDATE_BRANDS',
  DELETE_BRANDS: 'DELETE_BRANDS',

  // Unit Management
  CREATE_UNITS: 'CREATE_UNITS',
  UNITS_READ: 'UNITS_READ',
  UPDATE_UNITS: 'UPDATE_UNITS',
  DELETE_UNITS: 'DELETE_UNITS',

  // Stock Management
  STOCK_READ: 'STOCK_READ',
  SERIAL_NUMBERS_READ: 'SERIAL_NUMBERS_READ',
  TRANSFERS_READ: 'TRANSFERS_READ',
  TRANSFERS_CREATE: 'TRANSFERS_CREATE',
  ADJUSTMENTS_READ: 'ADJUSTMENTS_READ',
  ADJUSTMENTS_CREATE: 'ADJUSTMENTS_CREATE',

  // General Dashboard
  DASHBOARD_READ: 'DASHBOARD_READ',

  // Tax Rates
  TAX_RATES_READ: 'TAX_RATES_READ',
  CREATE_TAX_RATES: 'CREATE_TAX_RATES',
  UPDATE_TAX_RATES: 'UPDATE_TAX_RATES',
  DELETE_TAX_RATES: 'DELETE_TAX_RATES',

  // Profile & Company
  PROFILE_READ: 'PROFILE_READ',
  COMPANY_READ: 'COMPANY_READ',
  PASSWORD_READ: 'PASSWORD_READ',

  // Returns & Orders
  RETURNS_READ: 'RETURNS_READ',
  ORDERS_READ: 'ORDERS_READ',
  BLOGS_READ: 'BLOGS_READ',

  // Financial Management
  FINANCIAL_READ: 'FINANCIAL_READ',
  FINANCIAL_DASHBOARD_ACCESS: 'FINANCIAL_DASHBOARD_ACCESS',

  // Customer Financial Management
  CUSTOMER_RECEIVABLES_READ: 'CUSTOMER_RECEIVABLES_READ',
  CUSTOMER_RECEIVABLES_MANAGE: 'CUSTOMER_RECEIVABLES_MANAGE',
  CUSTOMER_PAYMENTS_PROCESS: 'CUSTOMER_PAYMENTS_PROCESS',
  CUSTOMER_CREDIT_MANAGE: 'CUSTOMER_CREDIT_MANAGE',
  CUSTOMER_AGING_REPORT: 'CUSTOMER_AGING_REPORT',

  // Sales Financial Analysis
  SALES_ANALYTICS_READ: 'SALES_ANALYTICS_READ',
  SALES_PERFORMANCE_READ: 'SALES_PERFORMANCE_READ',
  REVENUE_REPORTS: 'REVENUE_REPORTS',
  SALES_TRENDS_READ: 'SALES_TRENDS_READ',

  // Cost & Purchase Analytics
  COST_ANALYTICS_READ: 'COST_ANALYTICS_READ',
  PURCHASE_ANALYTICS_READ: 'PURCHASE_ANALYTICS_READ',

  // Commercial Agent Management
  COMMERCIAL_AGENTS_READ: 'COMMERCIAL_AGENTS_READ',
  COMMERCIAL_AGENTS_CREATE: 'COMMERCIAL_AGENTS_CREATE',
  COMMERCIAL_AGENTS_UPDATE: 'COMMERCIAL_AGENTS_UPDATE',
  COMMERCIAL_AGENTS_DELETE: 'COMMERCIAL_AGENTS_DELETE',
  AGENT_TRANSACTIONS_READ: 'AGENT_TRANSACTIONS_READ',
  AGENT_TRANSACTIONS_CREATE: 'AGENT_TRANSACTIONS_CREATE',
  AGENT_TRANSACTIONS_RECONCILE: 'AGENT_TRANSACTIONS_RECONCILE',
  AGENT_SETTLEMENTS_READ: 'AGENT_SETTLEMENTS_READ',
  AGENT_SETTLEMENTS_CREATE: 'AGENT_SETTLEMENTS_CREATE',
  INVENTORY_COST_READ: 'INVENTORY_COST_READ',
  SUPPLIER_PAYMENTS_READ: 'SUPPLIER_PAYMENTS_READ',
  SUPPLIER_PAYMENTS_MANAGE: 'SUPPLIER_PAYMENTS_MANAGE',
  SUPPLIER_PAYABLES_READ: 'SUPPLIER_PAYABLES_READ',

  // Profitability Analysis
  PROFIT_ANALYTICS_READ: 'PROFIT_ANALYTICS_READ',
  PROFITABILITY_ANALYTICS_READ: 'PROFITABILITY_ANALYTICS_READ',
  MARGIN_ANALYSIS_READ: 'MARGIN_ANALYSIS_READ',
  PROFITABILITY_REPORTS: 'PROFITABILITY_REPORTS',
  BREAK_EVEN_ANALYSIS: 'BREAK_EVEN_ANALYSIS',

  // Cash Flow Management
  CASH_FLOW_READ: 'CASH_FLOW_READ',
  CASH_POSITION_READ: 'CASH_POSITION_READ',
  CASH_PROJECTIONS_READ: 'CASH_PROJECTIONS_READ',

  // Financial Reporting
  FINANCIAL_REPORTS_READ: 'FINANCIAL_REPORTS_READ',
  FINANCIAL_REPORTS_EXPORT: 'FINANCIAL_REPORTS_EXPORT',
  FINANCIAL_ALERTS_READ: 'FINANCIAL_ALERTS_READ',
  FINANCIAL_KPI_READ: 'FINANCIAL_KPI_READ',

  // Analytics & Finance
  ANALYTICS_READ: 'ANALYTICS_READ',
  FINANCE_READ: 'FINANCE_READ',
  CASH_DRAWER_READ: 'CASH_DRAWER_READ',
  CASH_SYSTEM_READ: 'CASH_SYSTEM_READ',

  // POS Sessions
  NEW_POS_SESSION_READ: 'NEW_POS_SESSION_READ',
  POS_STATION_READ: 'POS_STATION_READ',
  SESSION_POS_SYNC_READ: 'SESSION_POS_SYNC_READ',

  // Purchase Order Workflow
  PURCHASE_ORDER_WORKFLOW_READ: 'PURCHASE_ORDER_WORKFLOW_READ',

  // Recent Inventory
  RECENT_INVENTORY_READ: 'RECENT_INVENTORY_READ',

  // Admin
  ADMIN_READ: 'ADMIN_READ',

  // Suppliers System
  SUPPLIERS_SYSTEM_READ: 'SUPPLIERS_SYSTEM_READ',

  // Purchase Orders
  CREATE_PURCHASE_ORDERS: 'CREATE_PURCHASE_ORDERS',
  READ_PURCHASE_ORDERS: 'READ_PURCHASE_ORDERS',
  UPDATE_PURCHASE_ORDERS: 'UPDATE_PURCHASE_ORDERS',
  DELETE_PURCHASE_ORDERS: 'DELETE_PURCHASE_ORDERS',
  APPROVE_PURCHASE_ORDERS: 'APPROVE_PURCHASE_ORDERS',
  VIEW_PURCHASE_REPORTS: 'VIEW_PURCHASE_REPORTS',

  // Sales Orders
  CREATE_SALES_ORDERS: 'CREATE_SALES_ORDERS',
  READ_SALES_ORDERS: 'READ_SALES_ORDERS',
  UPDATE_SALES_ORDERS: 'UPDATE_SALES_ORDERS',
  DELETE_SALES_ORDERS: 'DELETE_SALES_ORDERS',
  PROCESS_SALES: 'PROCESS_SALES',
  VIEW_SALES_REPORTS: 'VIEW_SALES_REPORTS',

  // Stock Management
  CREATE_STOCK_ADJUSTMENTS: 'CREATE_STOCK_ADJUSTMENTS',
  APPROVE_STOCK_ADJUSTMENTS: 'APPROVE_STOCK_ADJUSTMENTS',
  CREATE_STOCK_TRANSFERS: 'CREATE_STOCK_TRANSFERS',
  APPROVE_STOCK_TRANSFERS: 'APPROVE_STOCK_TRANSFERS',
  PURCHASES_ORDERS_RECEIVE: 'purchases.orders.receive',

  // Supplier Management
  CREATE_SUPPLIERS: 'CREATE_SUPPLIERS',
  READ_SUPPLIERS: 'READ_SUPPLIERS',
  UPDATE_SUPPLIERS: 'UPDATE_SUPPLIERS',
  DELETE_SUPPLIERS: 'DELETE_SUPPLIERS',

  // Customer Management
  CREATE_CUSTOMERS: 'CREATE_CUSTOMERS',
  READ_CUSTOMERS: 'READ_CUSTOMERS',
  UPDATE_CUSTOMERS: 'UPDATE_CUSTOMERS',
  DELETE_CUSTOMERS: 'DELETE_CUSTOMERS',

  // POS Operations
  OPERATE_POS: 'OPERATE_POS',
  MANAGE_POS_SESSIONS: 'MANAGE_POS_SESSIONS',
  MANAGE_CASH_DRAWER: 'MANAGE_CASH_DRAWER',
  PROCESS_PAYMENTS: 'PROCESS_PAYMENTS',
  PROCESS_REFUNDS: 'PROCESS_REFUNDS',
  VIEW_POS_REPORTS: 'VIEW_POS_REPORTS',

  // Financial Reports
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  EXPORT_DATA: 'EXPORT_DATA',

  // Comprehensive Financial Reporting System
  // Financial Statements
  VIEW_INCOME_STATEMENT: 'VIEW_INCOME_STATEMENT',
  VIEW_BALANCE_SHEET: 'VIEW_BALANCE_SHEET',
  VIEW_CASH_FLOW_STATEMENT: 'VIEW_CASH_FLOW_STATEMENT',
  GENERATE_FINANCIAL_STATEMENTS: 'GENERATE_FINANCIAL_STATEMENTS',
  APPROVE_FINANCIAL_STATEMENTS: 'APPROVE_FINANCIAL_STATEMENTS',
  PUBLISH_FINANCIAL_STATEMENTS: 'PUBLISH_FINANCIAL_STATEMENTS',

  // Journal Entries & General Ledger
  VIEW_GENERAL_LEDGER: 'VIEW_GENERAL_LEDGER',
  VIEW_CHART_OF_ACCOUNTS: 'VIEW_CHART_OF_ACCOUNTS',
  CREATE_JOURNAL_ENTRIES: 'CREATE_JOURNAL_ENTRIES',
  VIEW_JOURNAL_ENTRIES: 'VIEW_JOURNAL_ENTRIES',
  APPROVE_JOURNAL_ENTRIES: 'APPROVE_JOURNAL_ENTRIES',
  POST_JOURNAL_ENTRIES: 'POST_JOURNAL_ENTRIES',
  REVERSE_JOURNAL_ENTRIES: 'REVERSE_JOURNAL_ENTRIES',

  // Financial Analysis & Ratios
  VIEW_FINANCIAL_RATIOS: 'VIEW_FINANCIAL_RATIOS',
  VIEW_FINANCIAL_TRENDS: 'VIEW_FINANCIAL_TRENDS',
  VIEW_FINANCIAL_FORECASTS: 'VIEW_FINANCIAL_FORECASTS',
  GENERATE_FINANCIAL_FORECASTS: 'GENERATE_FINANCIAL_FORECASTS',
  VIEW_DUPONT_ANALYSIS: 'VIEW_DUPONT_ANALYSIS',

  // Budget & Variance Management
  VIEW_BUDGETS: 'VIEW_BUDGETS',
  CREATE_BUDGETS: 'CREATE_BUDGETS',
  APPROVE_BUDGETS: 'APPROVE_BUDGETS',
  VIEW_BUDGET_VARIANCE: 'VIEW_BUDGET_VARIANCE',

  // Audit & Compliance
  VIEW_FINANCIAL_AUDIT_TRAIL: 'VIEW_FINANCIAL_AUDIT_TRAIL',
  VIEW_COMPLIANCE_STATUS: 'VIEW_COMPLIANCE_STATUS',
  MANAGE_FINANCIAL_CONTROLS: 'MANAGE_FINANCIAL_CONTROLS',
  PERFORM_SOX_TESTING: 'PERFORM_SOX_TESTING',

  // Financial Administration
  CONFIGURE_FINANCIAL_SYSTEM: 'CONFIGURE_FINANCIAL_SYSTEM',
  MANAGE_FINANCIAL_PERMISSIONS: 'MANAGE_FINANCIAL_PERMISSIONS',
  VIEW_FINANCIAL_DASHBOARD: 'VIEW_FINANCIAL_DASHBOARD',

  // Period Management
  MANAGE_FINANCIAL_PERIODS: 'MANAGE_FINANCIAL_PERIODS',
  CLOSE_FINANCIAL_PERIODS: 'CLOSE_FINANCIAL_PERIODS',

  // Cash Management
  VIEW_CASH_MANAGEMENT: 'VIEW_CASH_MANAGEMENT',
  MANAGE_CASH_TRANSACTIONS: 'MANAGE_CASH_TRANSACTIONS',

  // System Administration
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_INTEGRATIONS: 'MANAGE_INTEGRATIONS',

  // Payroll Management
  PAYROLL_READ: 'PAYROLL_READ',
  PAYROLL_CREATE: 'PAYROLL_CREATE',
  PAYROLL_UPDATE: 'PAYROLL_UPDATE',
  PAYROLL_DELETE: 'PAYROLL_DELETE',
  PAYROLL_PROCESS: 'PAYROLL_PROCESS',
  PAYROLL_APPROVE: 'PAYROLL_APPROVE',
  PAYROLL_REPORTS_READ: 'PAYROLL_REPORTS_READ',
  PAYROLL_ANALYTICS_READ: 'PAYROLL_ANALYTICS_READ',
  EMPLOYEE_SALARY_READ: 'EMPLOYEE_SALARY_READ',
  EMPLOYEE_SALARY_UPDATE: 'EMPLOYEE_SALARY_UPDATE',
  PAYROLL_EXPORT: 'PAYROLL_EXPORT',

  // Presence Monitoring
  PRESENCE_READ: 'PRESENCE_READ',
  PRESENCE_CLOCK: 'PRESENCE_CLOCK',
  PRESENCE_REPORTS_READ: 'PRESENCE_REPORTS_READ',
  PRESENCE_ALERTS_READ: 'PRESENCE_ALERTS_READ',
  PRESENCE_TEAM_READ: 'PRESENCE_TEAM_READ',

  // Employee Presence Monitoring
  VIEW_OWN_PRESENCE: 'VIEW_OWN_PRESENCE',
  CLOCK_IN_OUT: 'CLOCK_IN_OUT',
  MANAGE_OWN_BREAKS: 'MANAGE_OWN_BREAKS',
  VIEW_OWN_SCHEDULE: 'VIEW_OWN_SCHEDULE',
  VIEW_OWN_ATTENDANCE_REPORTS: 'VIEW_OWN_ATTENDANCE_REPORTS',
  VIEW_OWN_PRESENCE_ALERTS: 'VIEW_OWN_PRESENCE_ALERTS',

  // Team Presence Management
  VIEW_TEAM_PRESENCE: 'VIEW_TEAM_PRESENCE',
  VIEW_TEAM_OVERVIEW: 'VIEW_TEAM_OVERVIEW',
  MANAGE_TEAM_ALERTS: 'MANAGE_TEAM_ALERTS',
  VIEW_TEAM_ATTENDANCE_REPORTS: 'VIEW_TEAM_ATTENDANCE_REPORTS',
  VIEW_TEAM_PRESENCE_ALERTS: 'VIEW_TEAM_PRESENCE_ALERTS',
  RESOLVE_PRESENCE_ALERTS: 'RESOLVE_PRESENCE_ALERTS',

  // Schedule Management
  VIEW_SCHEDULES: 'VIEW_SCHEDULES',
  CREATE_SCHEDULES: 'CREATE_SCHEDULES',
  UPDATE_SCHEDULES: 'UPDATE_SCHEDULES',
  DELETE_SCHEDULES: 'DELETE_SCHEDULES',
  MANAGE_ALL_SCHEDULES: 'MANAGE_ALL_SCHEDULES',

  // Attendance Reports
  VIEW_ORG_ATTENDANCE_REPORTS: 'VIEW_ORG_ATTENDANCE_REPORTS',
  GENERATE_ATTENDANCE_REPORTS: 'GENERATE_ATTENDANCE_REPORTS',
  MANAGE_ATTENDANCE_REPORTS: 'MANAGE_ATTENDANCE_REPORTS',

  // Administrative Presence Permissions
  OVERRIDE_CLOCK_ACTIONS: 'OVERRIDE_CLOCK_ACTIONS',
  EDIT_PRESENCE_SESSIONS: 'EDIT_PRESENCE_SESSIONS',
  EXPORT_PRESENCE_DATA: 'EXPORT_PRESENCE_DATA',
  MANAGE_PRESENCE_SYSTEM_SETTINGS: 'MANAGE_PRESENCE_SYSTEM_SETTINGS',
  MANAGE_ALL_PRESENCE_ALERTS: 'MANAGE_ALL_PRESENCE_ALERTS',

  // Production System Permissions
  PRODUCTION_READ: 'PRODUCTION_READ',
  PRODUCTION_CREATE: 'PRODUCTION_CREATE',
  PRODUCTION_UPDATE: 'PRODUCTION_UPDATE',
  PRODUCTION_DELETE: 'PRODUCTION_DELETE',
  PRODUCTION_START: 'PRODUCTION_START',
  PRODUCTION_STOP: 'PRODUCTION_STOP',
  PRODUCTION_QUALITY_CHECK: 'PRODUCTION_QUALITY_CHECK',
  PRODUCTION_COMPLETE: 'PRODUCTION_COMPLETE',
  PRODUCTION_REPORTS: 'PRODUCTION_REPORTS',
  PRODUCTION_ANALYTICS: 'PRODUCTION_ANALYTICS',

  // Recipe Management
  RECIPE_READ: 'RECIPE_READ',
  RECIPE_CREATE: 'RECIPE_CREATE',
  RECIPE_UPDATE: 'RECIPE_UPDATE',
  RECIPE_DELETE: 'RECIPE_DELETE',
  RECIPE_APPROVE: 'RECIPE_APPROVE',
  RECIPE_ARCHIVE: 'RECIPE_ARCHIVE',

  // Raw Materials Management
  RAW_MATERIALS_READ: 'RAW_MATERIALS_READ',
  RAW_MATERIALS_CREATE: 'RAW_MATERIALS_CREATE',
  RAW_MATERIALS_UPDATE: 'RAW_MATERIALS_UPDATE',
  RAW_MATERIALS_DELETE: 'RAW_MATERIALS_DELETE',
  RAW_MATERIALS_USAGE: 'RAW_MATERIALS_USAGE',

  // Production Planning
  PRODUCTION_PLANNING_READ: 'PRODUCTION_PLANNING_READ',
  PRODUCTION_PLANNING_CREATE: 'PRODUCTION_PLANNING_CREATE',
  PRODUCTION_PLANNING_UPDATE: 'PRODUCTION_PLANNING_UPDATE',
  PRODUCTION_PLANNING_DELETE: 'PRODUCTION_PLANNING_DELETE',
  PRODUCTION_PLANNING_APPROVE: 'PRODUCTION_PLANNING_APPROVE',

  // Production Costing
  PRODUCTION_COSTING_READ: 'PRODUCTION_COSTING_READ',
  PRODUCTION_COSTING_MANAGE: 'PRODUCTION_COSTING_MANAGE',
  PRODUCTION_COST_ANALYSIS: 'PRODUCTION_COST_ANALYSIS',

  // Profitability Analysis
  PRODUCTION_PROFITABILITY_READ: 'PRODUCTION_PROFITABILITY_READ',
  PRODUCTION_PROFITABILITY_MANAGE: 'PRODUCTION_PROFITABILITY_MANAGE',
  PRODUCTION_MARGIN_ANALYSIS: 'PRODUCTION_MARGIN_ANALYSIS',

  // Production Dashboard
  PRODUCTION_DASHBOARD_READ: 'PRODUCTION_DASHBOARD_READ',
  PRODUCTION_TRACKING_READ: 'PRODUCTION_TRACKING_READ',
  PRODUCTION_TRACKING_MANAGE: 'PRODUCTION_TRACKING_MANAGE',
} as const;

export type Permission = string;

// Predefined role templates with permissions
export const ROLE_TEMPLATES = {
  SUPER_ADMIN: {
    name: 'Super Administrator',
    code: 'super_admin',
    description: 'Full system access with all permissions',
    permissions: ['*', ...Object.values(PERMISSIONS)], // Wildcard + all individual permissions
    hierarchy: 1,
  },

  ADMIN: {
    name: 'Administrator',
    code: 'administrator',
    description: 'Organization administrator with full business access',
    permissions: [
      PERMISSIONS.VIEW_ORGANIZATION_SETTINGS,
      PERMISSIONS.CREATE_USERS,
      PERMISSIONS.READ_USERS,
      PERMISSIONS.UPDATE_USERS,
      PERMISSIONS.DEACTIVATE_USERS,
      PERMISSIONS.CREATE_ROLES,
      PERMISSIONS.READ_ROLES,
      PERMISSIONS.UPDATE_ROLES,
      PERMISSIONS.ASSIGN_ROLES,
      PERMISSIONS.CREATE_LOCATIONS,
      PERMISSIONS.READ_LOCATIONS,
      PERMISSIONS.UPDATE_LOCATIONS,
      PERMISSIONS.MANAGE_LOCATION_SETTINGS,
      PERMISSIONS.CREATE_ITEMS,
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.UPDATE_ITEMS,
      PERMISSIONS.DELETE_ITEMS,
      PERMISSIONS.MANAGE_INVENTORY_LEVELS,
      PERMISSIONS.VIEW_INVENTORY_REPORTS,
      PERMISSIONS.CREATE_CATEGORIES,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.UPDATE_CATEGORIES,
      PERMISSIONS.DELETE_CATEGORIES,
      PERMISSIONS.CREATE_PURCHASE_ORDERS,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.UPDATE_PURCHASE_ORDERS,
      PERMISSIONS.APPROVE_PURCHASE_ORDERS,
      PERMISSIONS.VIEW_PURCHASE_REPORTS,
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.UPDATE_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.VIEW_SALES_REPORTS,
      PERMISSIONS.CREATE_STOCK_ADJUSTMENTS,
      PERMISSIONS.APPROVE_STOCK_ADJUSTMENTS,
      PERMISSIONS.CREATE_STOCK_TRANSFERS,
      PERMISSIONS.APPROVE_STOCK_TRANSFERS,
      PERMISSIONS.PURCHASES_ORDERS_RECEIVE,
      PERMISSIONS.CREATE_SUPPLIERS,
      PERMISSIONS.READ_SUPPLIERS,
      PERMISSIONS.UPDATE_SUPPLIERS,
      PERMISSIONS.CREATE_CUSTOMERS,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.UPDATE_CUSTOMERS,
      PERMISSIONS.VIEW_FINANCIAL_REPORTS,
      PERMISSIONS.VIEW_ANALYTICS,
      PERMISSIONS.EXPORT_DATA,

      // Retail Financial System - Admin access
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_DASHBOARD_ACCESS,
      PERMISSIONS.CUSTOMER_RECEIVABLES_READ,
      PERMISSIONS.CUSTOMER_RECEIVABLES_MANAGE,
      PERMISSIONS.CUSTOMER_PAYMENTS_PROCESS,
      PERMISSIONS.CUSTOMER_CREDIT_MANAGE,
      PERMISSIONS.CUSTOMER_AGING_REPORT,
      PERMISSIONS.SALES_ANALYTICS_READ,
      PERMISSIONS.SALES_PERFORMANCE_READ,
      PERMISSIONS.REVENUE_REPORTS,
      PERMISSIONS.SALES_TRENDS_READ,
      PERMISSIONS.COST_ANALYTICS_READ,
      PERMISSIONS.PURCHASE_ANALYTICS_READ,
      PERMISSIONS.INVENTORY_COST_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_MANAGE,
      PERMISSIONS.SUPPLIER_PAYABLES_READ,
      PERMISSIONS.PROFIT_ANALYTICS_READ,
      PERMISSIONS.PROFITABILITY_ANALYTICS_READ,
      PERMISSIONS.MARGIN_ANALYSIS_READ,
      PERMISSIONS.PROFITABILITY_REPORTS,
      PERMISSIONS.BREAK_EVEN_ANALYSIS,
      PERMISSIONS.CASH_FLOW_READ,
      PERMISSIONS.CASH_POSITION_READ,
      PERMISSIONS.CASH_PROJECTIONS_READ,
      PERMISSIONS.FINANCIAL_REPORTS_READ,
      PERMISSIONS.FINANCIAL_REPORTS_EXPORT,
      PERMISSIONS.FINANCIAL_ALERTS_READ,
      PERMISSIONS.FINANCIAL_KPI_READ,
      // Comprehensive Financial Reporting System - Admin access
      PERMISSIONS.VIEW_FINANCIAL_DASHBOARD,
      PERMISSIONS.VIEW_INCOME_STATEMENT,
      PERMISSIONS.VIEW_BALANCE_SHEET,
      PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      PERMISSIONS.GENERATE_FINANCIAL_STATEMENTS,
      PERMISSIONS.VIEW_GENERAL_LEDGER,
      PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      PERMISSIONS.APPROVE_JOURNAL_ENTRIES,
      PERMISSIONS.POST_JOURNAL_ENTRIES,
      PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      PERMISSIONS.VIEW_BUDGETS,
      PERMISSIONS.CREATE_BUDGETS,
      PERMISSIONS.APPROVE_BUDGETS,
      PERMISSIONS.VIEW_BUDGET_VARIANCE,
      PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      PERMISSIONS.VIEW_COMPLIANCE_STATUS,
      PERMISSIONS.MANAGE_FINANCIAL_CONTROLS,
      PERMISSIONS.CONFIGURE_FINANCIAL_SYSTEM,
      PERMISSIONS.MANAGE_FINANCIAL_PERMISSIONS,
      PERMISSIONS.MANAGE_FINANCIAL_PERIODS,
      PERMISSIONS.CLOSE_FINANCIAL_PERIODS,
      PERMISSIONS.VIEW_CASH_MANAGEMENT,
      PERMISSIONS.MANAGE_CASH_TRANSACTIONS,
      // Presence Management - Admin access
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE,
      PERMISSIONS.VIEW_TEAM_OVERVIEW,
      PERMISSIONS.MANAGE_TEAM_ALERTS,
      PERMISSIONS.VIEW_TEAM_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE_ALERTS,
      PERMISSIONS.RESOLVE_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_SCHEDULES,
      PERMISSIONS.CREATE_SCHEDULES,
      PERMISSIONS.UPDATE_SCHEDULES,
      PERMISSIONS.DELETE_SCHEDULES,
      PERMISSIONS.MANAGE_ALL_SCHEDULES,
      PERMISSIONS.VIEW_ORG_ATTENDANCE_REPORTS,
      PERMISSIONS.GENERATE_ATTENDANCE_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE_REPORTS,
      PERMISSIONS.OVERRIDE_CLOCK_ACTIONS,
      PERMISSIONS.EDIT_PRESENCE_SESSIONS,
      PERMISSIONS.EXPORT_PRESENCE_DATA,
      PERMISSIONS.MANAGE_ALL_PRESENCE_ALERTS,
      // Legacy presence permissions for sidebar
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_CLOCK,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
      PERMISSIONS.PRESENCE_TEAM_READ,
      // Payroll Management - Admin access
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.PAYROLL_DELETE,
      PERMISSIONS.PAYROLL_PROCESS,
      PERMISSIONS.PAYROLL_APPROVE,
      PERMISSIONS.PAYROLL_REPORTS_READ,
      PERMISSIONS.PAYROLL_ANALYTICS_READ,
      PERMISSIONS.EMPLOYEE_SALARY_READ,
      PERMISSIONS.EMPLOYEE_SALARY_UPDATE,
      PERMISSIONS.PAYROLL_EXPORT,
      // Production System - Admin access
      PERMISSIONS.PRODUCTION_READ,
      PERMISSIONS.PRODUCTION_CREATE,
      PERMISSIONS.PRODUCTION_UPDATE,
      PERMISSIONS.PRODUCTION_DELETE,
      PERMISSIONS.PRODUCTION_START,
      PERMISSIONS.PRODUCTION_STOP,
      PERMISSIONS.PRODUCTION_QUALITY_CHECK,
      PERMISSIONS.PRODUCTION_COMPLETE,
      PERMISSIONS.PRODUCTION_REPORTS,
      PERMISSIONS.PRODUCTION_ANALYTICS,
      PERMISSIONS.RECIPE_READ,
      PERMISSIONS.RECIPE_CREATE,
      PERMISSIONS.RECIPE_UPDATE,
      PERMISSIONS.RECIPE_DELETE,
      PERMISSIONS.RECIPE_APPROVE,
      PERMISSIONS.RECIPE_ARCHIVE,
      PERMISSIONS.RAW_MATERIALS_READ,
      PERMISSIONS.RAW_MATERIALS_CREATE,
      PERMISSIONS.RAW_MATERIALS_UPDATE,
      PERMISSIONS.RAW_MATERIALS_DELETE,
      PERMISSIONS.RAW_MATERIALS_USAGE,
      PERMISSIONS.PRODUCTION_PLANNING_READ,
      PERMISSIONS.PRODUCTION_PLANNING_CREATE,
      PERMISSIONS.PRODUCTION_PLANNING_UPDATE,
      PERMISSIONS.PRODUCTION_PLANNING_DELETE,
      PERMISSIONS.PRODUCTION_PLANNING_APPROVE,
      PERMISSIONS.PRODUCTION_COSTING_READ,
      PERMISSIONS.PRODUCTION_COSTING_MANAGE,
      PERMISSIONS.PRODUCTION_COST_ANALYSIS,
      PERMISSIONS.PRODUCTION_PROFITABILITY_READ,
      PERMISSIONS.PRODUCTION_PROFITABILITY_MANAGE,
      PERMISSIONS.PRODUCTION_MARGIN_ANALYSIS,
      PERMISSIONS.PRODUCTION_DASHBOARD_READ,
      PERMISSIONS.PRODUCTION_TRACKING_READ,
      PERMISSIONS.PRODUCTION_TRACKING_MANAGE,
    ],
    hierarchy: 2,
  },

  MANAGER: {
    name: 'Manager',
    code: 'manager',
    description: 'Location or department manager with operational access',
    permissions: [
      PERMISSIONS.READ_USERS,
      PERMISSIONS.READ_LOCATIONS,
      PERMISSIONS.CREATE_ITEMS,
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.UPDATE_ITEMS,
      PERMISSIONS.MANAGE_INVENTORY_LEVELS,
      PERMISSIONS.VIEW_INVENTORY_REPORTS,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.CREATE_PURCHASE_ORDERS,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.UPDATE_PURCHASE_ORDERS,
      PERMISSIONS.VIEW_PURCHASE_REPORTS,
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.UPDATE_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.VIEW_SALES_REPORTS,
      PERMISSIONS.CREATE_STOCK_ADJUSTMENTS,
      PERMISSIONS.CREATE_STOCK_TRANSFERS,
      PERMISSIONS.PURCHASES_ORDERS_RECEIVE,
      PERMISSIONS.READ_SUPPLIERS,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.UPDATE_CUSTOMERS,
      PERMISSIONS.OPERATE_POS,
      PERMISSIONS.MANAGE_POS_SESSIONS,
      PERMISSIONS.MANAGE_CASH_DRAWER,
      PERMISSIONS.PROCESS_PAYMENTS,
      PERMISSIONS.PROCESS_REFUNDS,
      PERMISSIONS.VIEW_POS_REPORTS,

      // Retail Financial System - Manager access
      PERMISSIONS.FINANCIAL_READ,
      PERMISSIONS.FINANCIAL_DASHBOARD_ACCESS,
      PERMISSIONS.CUSTOMER_RECEIVABLES_READ,
      PERMISSIONS.CUSTOMER_RECEIVABLES_MANAGE,
      PERMISSIONS.CUSTOMER_PAYMENTS_PROCESS,
      PERMISSIONS.CUSTOMER_AGING_REPORT,
      PERMISSIONS.SALES_ANALYTICS_READ,
      PERMISSIONS.SALES_PERFORMANCE_READ,
      PERMISSIONS.REVENUE_REPORTS,
      PERMISSIONS.SALES_TRENDS_READ,
      PERMISSIONS.COST_ANALYTICS_READ,
      PERMISSIONS.PURCHASE_ANALYTICS_READ,
      PERMISSIONS.INVENTORY_COST_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.SUPPLIER_PAYABLES_READ,
      PERMISSIONS.PROFIT_ANALYTICS_READ,
      PERMISSIONS.PROFITABILITY_ANALYTICS_READ,
      PERMISSIONS.MARGIN_ANALYSIS_READ,
      PERMISSIONS.PROFITABILITY_REPORTS,
      PERMISSIONS.CASH_FLOW_READ,
      PERMISSIONS.CASH_POSITION_READ,
      PERMISSIONS.FINANCIAL_REPORTS_READ,
      PERMISSIONS.FINANCIAL_ALERTS_READ,
      PERMISSIONS.FINANCIAL_KPI_READ,

      // Presence Management - Manager access
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE,
      PERMISSIONS.VIEW_TEAM_OVERVIEW,
      PERMISSIONS.MANAGE_TEAM_ALERTS,
      PERMISSIONS.VIEW_TEAM_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE_ALERTS,
      PERMISSIONS.RESOLVE_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_SCHEDULES,
      PERMISSIONS.CREATE_SCHEDULES,
      PERMISSIONS.UPDATE_SCHEDULES,
      PERMISSIONS.DELETE_SCHEDULES,
      PERMISSIONS.VIEW_ORG_ATTENDANCE_REPORTS,
      PERMISSIONS.GENERATE_ATTENDANCE_REPORTS,
      PERMISSIONS.EXPORT_PRESENCE_DATA,
      // Basic Financial Reporting - Manager access
      PERMISSIONS.VIEW_FINANCIAL_DASHBOARD,
      PERMISSIONS.VIEW_INCOME_STATEMENT,
      PERMISSIONS.VIEW_BALANCE_SHEET,
      PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      PERMISSIONS.VIEW_GENERAL_LEDGER,
      PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      PERMISSIONS.VIEW_BUDGETS,
      PERMISSIONS.VIEW_BUDGET_VARIANCE,
      PERMISSIONS.VIEW_CASH_MANAGEMENT,
      // Legacy presence permissions for sidebar
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_CLOCK,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
      PERMISSIONS.PRESENCE_TEAM_READ,
      // Payroll Management - Manager access
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_REPORTS_READ,
      PERMISSIONS.PAYROLL_ANALYTICS_READ,
      PERMISSIONS.EMPLOYEE_SALARY_READ,
      PERMISSIONS.PAYROLL_EXPORT,
      // Production System - Manager access
      PERMISSIONS.PRODUCTION_READ,
      PERMISSIONS.PRODUCTION_CREATE,
      PERMISSIONS.PRODUCTION_UPDATE,
      PERMISSIONS.PRODUCTION_START,
      PERMISSIONS.PRODUCTION_STOP,
      PERMISSIONS.PRODUCTION_QUALITY_CHECK,
      PERMISSIONS.PRODUCTION_COMPLETE,
      PERMISSIONS.PRODUCTION_REPORTS,
      PERMISSIONS.PRODUCTION_ANALYTICS,
      PERMISSIONS.RECIPE_READ,
      PERMISSIONS.RECIPE_CREATE,
      PERMISSIONS.RECIPE_UPDATE,
      PERMISSIONS.RAW_MATERIALS_READ,
      PERMISSIONS.RAW_MATERIALS_CREATE,
      PERMISSIONS.RAW_MATERIALS_UPDATE,
      PERMISSIONS.RAW_MATERIALS_USAGE,
      PERMISSIONS.PRODUCTION_PLANNING_READ,
      PERMISSIONS.PRODUCTION_PLANNING_CREATE,
      PERMISSIONS.PRODUCTION_PLANNING_UPDATE,
      PERMISSIONS.PRODUCTION_COSTING_READ,
      PERMISSIONS.PRODUCTION_COSTING_MANAGE,
      PERMISSIONS.PRODUCTION_COST_ANALYSIS,
      PERMISSIONS.PRODUCTION_PROFITABILITY_READ,
      PERMISSIONS.PRODUCTION_MARGIN_ANALYSIS,
      PERMISSIONS.PRODUCTION_DASHBOARD_READ,
      PERMISSIONS.PRODUCTION_TRACKING_READ,
      PERMISSIONS.PRODUCTION_TRACKING_MANAGE,
    ],
    hierarchy: 3,
  },

  SUPERVISOR: {
    name: 'Supervisor',
    code: 'supervisor',
    description: 'Shift supervisor with limited management capabilities',
    permissions: [
      PERMISSIONS.READ_USERS,
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.UPDATE_ITEMS,
      PERMISSIONS.VIEW_INVENTORY_REPORTS,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.UPDATE_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.CREATE_STOCK_ADJUSTMENTS,
      PERMISSIONS.PURCHASES_ORDERS_RECEIVE,
      PERMISSIONS.READ_SUPPLIERS,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.UPDATE_CUSTOMERS,
      PERMISSIONS.OPERATE_POS,
      PERMISSIONS.MANAGE_POS_SESSIONS,
      PERMISSIONS.MANAGE_CASH_DRAWER,
      PERMISSIONS.PROCESS_PAYMENTS,
      PERMISSIONS.PROCESS_REFUNDS,
      // Presence Management - Supervisor access
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE,
      PERMISSIONS.VIEW_TEAM_OVERVIEW,
      PERMISSIONS.RESOLVE_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_SCHEDULES,
      // Legacy presence permissions for sidebar
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_CLOCK,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
      PERMISSIONS.PRESENCE_TEAM_READ,
      // Basic Payroll Management - Supervisor access (read-only)
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_REPORTS_READ,
      PERMISSIONS.EMPLOYEE_SALARY_READ,
    ],
    hierarchy: 4,
  },

  EMPLOYEE: {
    name: 'Employee',
    code: 'employee',
    description: 'General employee with basic operational access',
    permissions: [
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.OPERATE_POS,
      PERMISSIONS.PROCESS_PAYMENTS,

      // Limited Financial Access - Employee
      PERMISSIONS.SALES_PERFORMANCE_READ, // Can see basic sales info
      PERMISSIONS.CUSTOMER_RECEIVABLES_READ, // Can view customer balances (for sales)

      // Presence Management - Employee access
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      // Legacy presence permissions for sidebar
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_CLOCK,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
      // Basic Payroll Management - Employee access (own data only)
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.EMPLOYEE_SALARY_READ,
    ],
    hierarchy: 5,
  },

  CASHIER: {
    name: 'Cashier',
    code: 'cashier',
    description: 'POS operator with point-of-sale access only',
    permissions: [
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.OPERATE_POS,
      PERMISSIONS.PROCESS_PAYMENTS,
      PERMISSIONS.PROCESS_REFUNDS,

      // Minimal Financial Access - Cashier
      PERMISSIONS.CUSTOMER_RECEIVABLES_READ, // Can view customer balances for payment collection

      // Presence Management - Cashier access
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      // Legacy presence permissions for sidebar
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_CLOCK,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
    ],
    hierarchy: 6,
  },

  VIEWER: {
    name: 'Viewer',
    code: 'viewer',
    description: 'Read-only access for reporting and monitoring',
    permissions: [
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.READ_SUPPLIERS,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.VIEW_INVENTORY_REPORTS,
      PERMISSIONS.VIEW_SALES_REPORTS,
      PERMISSIONS.VIEW_POS_REPORTS,
      // Presence Management - Viewer access (read-only)
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      // Legacy presence permissions for sidebar (read-only)
      PERMISSIONS.PRESENCE_READ,
      PERMISSIONS.PRESENCE_REPORTS_READ,
      PERMISSIONS.PRESENCE_ALERTS_READ,
    ],
    hierarchy: 7,
  },
} as const;

// Permission groups for easier management
export const PERMISSION_GROUPS = {
  USER_MANAGEMENT: {
    name: 'User Management',
    permissions: [
      PERMISSIONS.CREATE_USERS,
      PERMISSIONS.READ_USERS,
      PERMISSIONS.UPDATE_USERS,
      PERMISSIONS.DELETE_USERS,
      PERMISSIONS.DEACTIVATE_USERS,
    ],
  },

  ROLE_MANAGEMENT: {
    name: 'Role Management',
    permissions: [
      PERMISSIONS.CREATE_ROLES,
      PERMISSIONS.READ_ROLES,
      PERMISSIONS.UPDATE_ROLES,
      PERMISSIONS.DELETE_ROLES,
      PERMISSIONS.ASSIGN_ROLES,
    ],
  },

  INVENTORY_MANAGEMENT: {
    name: 'Inventory Management',
    permissions: [
      PERMISSIONS.CREATE_ITEMS,
      PERMISSIONS.READ_ITEMS,
      PERMISSIONS.UPDATE_ITEMS,
      PERMISSIONS.DELETE_ITEMS,
      PERMISSIONS.MANAGE_INVENTORY_LEVELS,
      PERMISSIONS.VIEW_INVENTORY_REPORTS,
      PERMISSIONS.CREATE_CATEGORIES,
      PERMISSIONS.READ_CATEGORIES,
      PERMISSIONS.UPDATE_CATEGORIES,
      PERMISSIONS.DELETE_CATEGORIES,
    ],
  },

  PURCHASE_MANAGEMENT: {
    name: 'Purchase Management',
    permissions: [
      PERMISSIONS.CREATE_PURCHASE_ORDERS,
      PERMISSIONS.READ_PURCHASE_ORDERS,
      PERMISSIONS.UPDATE_PURCHASE_ORDERS,
      PERMISSIONS.DELETE_PURCHASE_ORDERS,
      PERMISSIONS.APPROVE_PURCHASE_ORDERS,
      PERMISSIONS.VIEW_PURCHASE_REPORTS,
      PERMISSIONS.PURCHASES_ORDERS_RECEIVE,
    ],
  },

  SALES_MANAGEMENT: {
    name: 'Sales Management',
    permissions: [
      PERMISSIONS.CREATE_SALES_ORDERS,
      PERMISSIONS.READ_SALES_ORDERS,
      PERMISSIONS.UPDATE_SALES_ORDERS,
      PERMISSIONS.DELETE_SALES_ORDERS,
      PERMISSIONS.PROCESS_SALES,
      PERMISSIONS.VIEW_SALES_REPORTS,
    ],
  },

  POS_OPERATIONS: {
    name: 'POS Operations',
    permissions: [
      PERMISSIONS.OPERATE_POS,
      PERMISSIONS.MANAGE_POS_SESSIONS,
      PERMISSIONS.MANAGE_CASH_DRAWER,
      PERMISSIONS.PROCESS_PAYMENTS,
      PERMISSIONS.PROCESS_REFUNDS,
      PERMISSIONS.VIEW_POS_REPORTS,
    ],
  },

  SUPPLIER_MANAGEMENT: {
    name: 'Supplier Management',
    permissions: [
      PERMISSIONS.CREATE_SUPPLIERS,
      PERMISSIONS.READ_SUPPLIERS,
      PERMISSIONS.UPDATE_SUPPLIERS,
      PERMISSIONS.DELETE_SUPPLIERS,
    ],
  },

  CUSTOMER_MANAGEMENT: {
    name: 'Customer Management',
    permissions: [
      PERMISSIONS.CREATE_CUSTOMERS,
      PERMISSIONS.READ_CUSTOMERS,
      PERMISSIONS.UPDATE_CUSTOMERS,
      PERMISSIONS.DELETE_CUSTOMERS,
    ],
  },

  REPORTS_ANALYTICS: {
    name: 'Reports & Analytics',
    permissions: [
      PERMISSIONS.VIEW_FINANCIAL_REPORTS,
      PERMISSIONS.VIEW_ANALYTICS,
      PERMISSIONS.EXPORT_DATA,
    ],
  },

  SYSTEM_ADMINISTRATION: {
    name: 'System Administration',
    permissions: [
      PERMISSIONS.MANAGE_ORGANIZATION,
      PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
      PERMISSIONS.VIEW_AUDIT_LOGS,
      PERMISSIONS.MANAGE_INTEGRATIONS,
    ],
  },

  PRESENCE_MONITORING: {
    name: 'Employee Presence Monitoring',
    permissions: [
      PERMISSIONS.VIEW_OWN_PRESENCE,
      PERMISSIONS.CLOCK_IN_OUT,
      PERMISSIONS.MANAGE_OWN_BREAKS,
      PERMISSIONS.VIEW_OWN_SCHEDULE,
      PERMISSIONS.VIEW_OWN_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_OWN_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE,
      PERMISSIONS.VIEW_TEAM_OVERVIEW,
      PERMISSIONS.MANAGE_TEAM_ALERTS,
      PERMISSIONS.VIEW_TEAM_ATTENDANCE_REPORTS,
      PERMISSIONS.VIEW_TEAM_PRESENCE_ALERTS,
      PERMISSIONS.RESOLVE_PRESENCE_ALERTS,
      PERMISSIONS.VIEW_SCHEDULES,
      PERMISSIONS.CREATE_SCHEDULES,
      PERMISSIONS.UPDATE_SCHEDULES,
      PERMISSIONS.DELETE_SCHEDULES,
      PERMISSIONS.MANAGE_ALL_SCHEDULES,
      PERMISSIONS.VIEW_ORG_ATTENDANCE_REPORTS,
      PERMISSIONS.GENERATE_ATTENDANCE_REPORTS,
      PERMISSIONS.MANAGE_ATTENDANCE_REPORTS,
      PERMISSIONS.OVERRIDE_CLOCK_ACTIONS,
      PERMISSIONS.EDIT_PRESENCE_SESSIONS,
      PERMISSIONS.EXPORT_PRESENCE_DATA,
      PERMISSIONS.MANAGE_PRESENCE_SYSTEM_SETTINGS,
      PERMISSIONS.MANAGE_ALL_PRESENCE_ALERTS,
    ],
  },
} as const;

export const permissions = Object.entries(PERMISSION_GROUPS).map(([name, group]) => ({
  name,
  display: group.name,
  permissions: Object.fromEntries(group.permissions.map((permission) => [permission, permission])),
}));

// Legacy types for backward compatibility
export type Role = "admin" | "administrator" | "super_admin" | "buyer" | "approver" | "receiver" | "manager" | "supervisor" | "employee" | "cashier" | "viewer"

type UserRoleLike =
  | string
  | {
      code?: string | null
      permissions?: string[] | null
    }

export type UserLike = {
  id: string
  email?: string | null
  name?: string | null
  roles?: UserRoleLike[]
  permissions?: string[]
}

export type Action =
  | "po:create"
  | "po:submit"
  | "po:approve"
  | "purchases.orders.receive"
  | "po:cancel"
  | "po:update"
  | "po:delete"
  | "po:clone"
  | "po:export"
  | "po:bulk-status"

const roleMatrix: Partial<Record<Role, Action[]>> = {
  admin: [
    "po:create",
    "po:submit",
    "po:approve",
    "purchases.orders.receive",
    "po:cancel",
    "po:update",
    "po:delete",
    "po:clone",
    "po:export",
    "po:bulk-status",
  ],
  buyer: ["po:create", "po:submit", "po:update", "po:clone", "po:export"],
  approver: ["po:approve", "po:cancel", "po:export", "po:bulk-status"],
  receiver: ["purchases.orders.receive", "po:export"],
  manager: ["po:create", "po:submit", "po:approve", "po:update", "po:clone", "po:export"],
  supervisor: ["po:create", "po:submit", "po:update", "po:clone", "po:export"],
  employee: ["po:create", "po:submit", "po:export"],
  cashier: ["po:export"],
  viewer: ["po:export"],
}

function roleCode(role: UserRoleLike): string | null {
  return typeof role === "string" ? role : role.code ?? null
}

function rolePermissions(role: UserRoleLike): string[] {
  return typeof role === "string" ? [] : role.permissions ?? []
}

// Legacy function for backward compatibility plus modern RBAC arrays.
export function can(user: UserLike | null | undefined, action: Action | string) {
  if (!user) return false

  const roles = user.roles ?? []
  const permissions = new Set([
    ...(user.permissions ?? []),
    ...roles.flatMap(rolePermissions),
  ])

  if (hasRbacPermission([...permissions], action)) return true

  const roleCodes = roles.map(roleCode).filter(Boolean) as Role[]
  if (roleCodes.some((code) => code === "admin" || code === "administrator" || code === "super_admin")) {
    return true
  }

  if (!roleCodes.length) return false
  return roleCodes.some((code) => roleMatrix[code]?.includes(action as Action))
}

// Helper functions for permission checking
export function hasPermission(userPermissions: string[], requiredPermission: string): boolean {
  return hasRbacPermission(userPermissions, requiredPermission);
}

export function hasAnyPermission(userPermissions: string[], requiredPermissions: string[]): boolean {
  return hasAnyRbacPermission(userPermissions, requiredPermissions);
}

export function hasAllPermissions(userPermissions: string[], requiredPermissions: string[]): boolean {
  return hasAllRbacPermissions(userPermissions, requiredPermissions);
}

export function getPermissionsByGroup(groupName: keyof typeof PERMISSION_GROUPS): string[] {
  return Array.from(PERMISSION_GROUPS[groupName].permissions);
}

export function getAllPermissions(): string[] {
  return Object.values(PERMISSIONS);
}

// Permission hierarchy checker
export function canManageUser(managerPermissions: string[], targetUserPermissions: string[]): boolean {
  // Super admins can manage anyone
  if (hasPermission(managerPermissions, PERMISSIONS.MANAGE_ORGANIZATION)) {
    return true;
  }

  // Admins can manage non-admin users
  if (hasPermission(managerPermissions, PERMISSIONS.CREATE_USERS)) {
    return !hasPermission(targetUserPermissions, PERMISSIONS.MANAGE_ORGANIZATION);
  }

  return false;
}

// Role hierarchy helper
export function getRoleHierarchy(roleCode: string): number {
  const role = Object.values(ROLE_TEMPLATES).find(r => r.code === roleCode);
  return role?.hierarchy || 999;
}

export function canManageRole(managerRoles: string[], targetRoleCode: string): boolean {
  const managerHierarchy = Math.min(...managerRoles.map(getRoleHierarchy));
  const targetHierarchy = getRoleHierarchy(targetRoleCode);

  return managerHierarchy < targetHierarchy;
}
