ALTER TYPE "AccountingPostingPurpose" ADD VALUE IF NOT EXISTS 'PAYMENT_RECONCILIATION';
ALTER TYPE "AccountingPostingPurpose" ADD VALUE IF NOT EXISTS 'SUSPENSE_RECLASSIFICATION';

ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'STOCK_COUNT';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'PAYMENT_RECONCILIATION';
ALTER TYPE "AccountingSourceType" ADD VALUE IF NOT EXISTS 'PAYMENT_SUSPENSE';

ALTER TYPE "PostingRuleAmountSource" ADD VALUE IF NOT EXISTS 'NET_PAYABLE_AMOUNT';
ALTER TYPE "PostingRuleAmountSource" ADD VALUE IF NOT EXISTS 'EMPLOYEE_DEDUCTION_AMOUNT';
ALTER TYPE "PostingRuleAmountSource" ADD VALUE IF NOT EXISTS 'EMPLOYER_CHARGE_AMOUNT';
