export type AuthLocale = "en" | "fr";

export function getAuthLocale(pathname: string): AuthLocale {
  return pathname.match(/^\/fr(?:\/|$)/) ? "fr" : "en";
}

export const authCopy = {
  en: {
    common: {
      brandSubtitle: "OHADA SMB OS",
      languageAria: "Switch language",
      switchToLight: "Switch to light theme",
      switchToDark: "Switch to dark theme",
      light: "Light",
      dark: "Dark",
      encrypted: "Tenant-scoped access",
      teamReady: "Module gates ready",
      permissionAware: "RBAC + step-up",
      processing: "Processing...",
      liveAccess: "Protected operating perimeter",
      workspaceSignal: "Evidence aware",
      trustTitle: "Auth protects operational truth",
      trustBody:
        "Every sign-in can open access to stock, cash, payroll, supplier payments, compliance evidence, and close work, so sessions stay tenant-scoped and permission-aware.",
      commandTitle: "Secure operating entry",
      commandBody: "One guarded entry point for cashiers, accountants, payroll teams, managers, and tenant administrators.",
      moduleShowcaseTitle: "What opens after sign-in",
      moduleShowcaseBody:
        "POS, inventory, purchasing/AP, accounting close, compliance, reconciliation, payroll/presence, offline sync, and controls are reached from the same protected workspace.",
      moduleHighlights: {
        pos: {
          label: "POS and cash drawers",
          body: "Open cashier sessions, sell, issue receipts, manage returns, and preserve drawer evidence.",
          metric: "Checkout",
        },
        inventory: {
          label: "Inventory evidence",
          body: "Track items, counts, transfers, write-offs, valuation signals, and location-level stock.",
          metric: "Stock proof",
        },
        purchasing: {
          label: "Purchasing/AP controls",
          body: "Coordinate POs, receiving, supplier invoices, matching, approvals, and payment release.",
          metric: "AP flow",
        },
        accounting: {
          label: "OHADA accounting close",
          body: "Keep chart, journals, posting rules, trial balance, source links, and close packs aligned.",
          metric: "Close",
        },
        compliance: {
          label: "Compliance country packs",
          body: "Govern fiscal documents, legal evidence, authority queues, and country-pack rules.",
          metric: "Rules",
        },
        reconciliation: {
          label: "Payment reconciliation",
          body: "Match provider evidence and statements, resolve suspense, and protect close readiness.",
          metric: "Suspense",
        },
        payroll: {
          label: "Payroll/presence",
          body: "Connect employees, contracts, attendance, leave, payroll runs, approvals, and postings.",
          metric: "People",
        },
        offline: {
          label: "Offline POS sync",
          body: "Preserve branch continuity with device identity, queued work, replay, and conflict review.",
          metric: "Replay",
        },
        controls: {
          label: "Tenant controls",
          body: "Enforce RBAC, step-up, maker-checker, module gates, and audit-friendly access.",
          metric: "RBAC",
        },
      },
      statusCards: {
        uptime: "Tenant scope",
        audit: "Source evidence",
        sync: "Offline replay",
      },
      capabilityCards: {
        inventory: "Inventory evidence",
        security: "Role security",
        insight: "Close insight",
      },
    },
    layout: {
      login: {
        eyebrow: "Protected access",
        title: "Sign in to the operating workspace",
        body: "Access the tenant-scoped workspace where stock, cash, close, reconciliation, payroll, and controls share one evidence trail.",
      },
      register: {
        eyebrow: "OHADA workspace onboarding",
        title: "Create the tenant that will run your operations",
        body: "Set up the organization, country context, administrator account, and module-ready workspace before inviting teams.",
      },
      forgot: {
        eyebrow: "Account recovery",
        title: "Recover access securely",
        body: "Reset credentials with the same safeguards used across the StockFlow platform.",
      },
      verify: {
        eyebrow: "Verification",
        title: "Confirm your account",
        body: "Complete verification and step into a protected operational workspace.",
      },
    },
    login: {
      badge: "Tenant sign in",
      title: "Access your operating workspace",
      subtitle: "Review today's POS, stock, finance, close, payroll, and control work from a tenant-scoped session.",
      email: "Email address",
      emailPlaceholder: "you@company.com",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      remember: "Remember me",
      forgot: "Forgot password?",
      submit: "Sign in securely",
      loading: "Signing in",
      newHere: "New to AqStoqFlow?",
      createAccount: "Create an account",
      secureNote: "Sessions are tenant-scoped and permission-aware because the workspace touches cash, stock, payroll, suppliers, compliance, and close.",
      methodTitle: "Email and password access",
      methodSubtitle: "Use the tenant-scoped password flow. Protected modules can still request fresh verification when needed.",
      sso: "Organization SSO",
      ssoHint: "Domain routed",
      passkey: "Passkey",
      passkeyHint: "Device verified",
      passwordMethod: "Password",
      passwordHint: "Standard access",
      unavailableTitle: "Method Not Enabled",
      unavailableBody: "This workspace is currently using email and password authentication.",
      unavailableHint: "Continue with the password form below.",
      divider: "or continue with password",
      accessLevel: "Tenant console",
      showPassword: "Show password",
      hidePassword: "Hide password",
      registeredTitle: "Check Your Email",
      registeredBody: "Your tenant workspace was created. Verify your email before signing in.",
      errors: {
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        authFailed: "Authentication Failed",
        verifyTitle: "Verification Required",
        verifyBody: "Please verify your email address before accessing the dashboard.",
        verifyHint: "Use the code sent to your inbox, then sign in again.",
        unexpectedTitle: "Unexpected Error",
        unexpectedBody: "An unexpected error occurred during login",
        tryAgain: "Please try again",
        attempt: "Attempt",
        connectionTitle: "Connection Error",
        connectionBody: "Unable to connect to authentication service. Please try again.",
        connectionHint: "Network or server error",
      },
      successTitle: "Signed in",
      successBody: "Workspace access verified.",
    },
    register: {
      badge: "Create tenant workspace",
      title: "Prepare an OHADA operating workspace",
      subtitle: "Capture the organization context used for modules, country packs, branch controls, and administrator access.",
      step: "Step",
      of: "of",
      steps: {
        personal: "Owner",
        company: "Tenant",
        security: "Access",
      },
      fields: {
        firstName: "First name",
        firstNamePlaceholder: "Jane",
        lastName: "Last name",
        lastNamePlaceholder: "Doe",
        email: "Work email",
        emailPlaceholder: "jane@company.com",
        phone: "Phone number",
        phonePlaceholder: "+1 555 0100",
        companyName: "Company name",
        companyNamePlaceholder: "AqStoq Retail Group",
        companySize: "Company size",
        selectCompanySize: "Select company size",
        industry: "Industry",
        selectIndustry: "Select industry",
        country: "Country",
        countryPlaceholder: "Cameroon",
        state: "State or province",
        statePlaceholder: "Centre",
        address: "Business address",
        addressPlaceholder: "Street, city, postal code",
        currency: "Default currency",
        timezone: "Timezone",
        defaultLocale: "Workspace language",
        password: "Password",
        passwordPlaceholder: "Create a strong password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Confirm password",
        termsPrefix: "I agree to the",
        terms: "Terms of Service",
        and: "and",
        privacy: "Privacy Policy",
      },
      companySizes: {
        small: "1-10 employees",
        medium: "11-50 employees",
        large: "51-200 employees",
        enterprise: "201+ employees",
      },
      infoBox:
        "AqStoqFlow creates your organization, assigns administrator access, and prepares a tenant-scoped workspace.",
      passwordStrength: "Password strength",
      passwordLevels: {
        developing: "Developing",
        strong: "Strong",
        excellent: "Excellent",
      },
      continue: "Continue",
      back: "Back",
      create: "Create account",
      creating: "Creating",
      already: "Already have an account?",
      signIn: "Sign in",
      showPassword: "Show password",
      hidePassword: "Hide password",
      warningTitle: "Complete This Step",
      warningBody: "Please fill in the required fields before continuing.",
      successTitle: "Account Created",
      successBody: "Please check your email to verify your account before signing in.",
      errorTitle: "Registration Failed",
      errorHint: "Please check your information and try again.",
      networkTitle: "Network Error",
      networkBody: "Unable to create account. Please try again.",
      networkHint: "Registration failed",
      blueprintTitle: "Operating workspace blueprint",
      blueprintBody: "AqStoqFlow prepares tenant scope, module gates, and evidence-ready defaults while you complete setup.",
      setupTime: "Guided setup",
      setupTrust: "Tenant admin security",
      blueprintItems: {
        organization: "Tenant organization created",
        admin: "Administrator access prepared",
        inventory: "POS, stock, AP, and controls prepared",
      },
      errors: {
        firstNameRequired: "First name is required",
        firstNameMin: "First name must be at least 2 characters",
        lastNameRequired: "Last name is required",
        lastNameMin: "Last name must be at least 2 characters",
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        phoneRequired: "Phone number is required",
        companyRequired: "Company name is required",
        companyMin: "Company name must be at least 2 characters",
        companySizeRequired: "Company size is required",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        confirmRequired: "Please confirm your password",
        confirmMismatch: "Passwords do not match",
        termsRequired: "You must accept the terms and conditions",
      },
    },
  },
  fr: {
    common: {
      brandSubtitle: "OS PME OHADA",
      languageAria: "Changer de langue",
      switchToLight: "Passer au theme clair",
      switchToDark: "Passer au theme sombre",
      light: "Clair",
      dark: "Sombre",
      encrypted: "Acces porte tenant",
      teamReady: "Gates modules prets",
      permissionAware: "RBAC + step-up",
      processing: "Traitement...",
      liveAccess: "Perimetre operationnel protege",
      workspaceSignal: "Preuve active",
      trustTitle: "L'auth protege la verite operationnelle",
      trustBody:
        "Chaque connexion peut ouvrir acces au stock, cash, paie, paiements fournisseurs, preuves de conformite et cloture ; les sessions restent donc portees tenant et permission-aware.",
      commandTitle: "Entree operationnelle securisee",
      commandBody: "Un point d'entree protege pour caissiers, comptables, paie, managers et administrateurs tenant.",
      moduleShowcaseTitle: "Ce qui s'ouvre apres connexion",
      moduleShowcaseBody:
        "PDV, inventaire, achats/AP, cloture comptable, conformite, rapprochement, paie/presence, sync hors ligne et controles sont accessibles depuis le meme espace protege.",
      moduleHighlights: {
        pos: {
          label: "PDV et tiroirs caisse",
          body: "Ouvrez sessions caissier, ventes, recus, retours et preuves de tiroir.",
          metric: "Caisse",
        },
        inventory: {
          label: "Preuve inventaire",
          body: "Suivez articles, comptages, transferts, sorties, valorisation et stock par site.",
          metric: "Preuve stock",
        },
        purchasing: {
          label: "Controles achats/AP",
          body: "Coordonnez BC, receptions, factures fournisseur, matching, validations et liberation paiement.",
          metric: "Flux AP",
        },
        accounting: {
          label: "Cloture comptable OHADA",
          body: "Gardez plan, journaux, regles d'ecriture, balance, sources et packs de cloture alignes.",
          metric: "Cloture",
        },
        compliance: {
          label: "Packs pays conformite",
          body: "Gouvernez documents fiscaux, preuves legales, files autorite et regles pays.",
          metric: "Regles",
        },
        reconciliation: {
          label: "Rapprochement paiements",
          body: "Matchez preuves prestataires et releves, resolvez suspenses et protegez la cloture.",
          metric: "Suspense",
        },
        payroll: {
          label: "Paie/presence",
          body: "Connectez employes, contrats, presence, conges, runs paie, validations et ecritures.",
          metric: "Equipe",
        },
        offline: {
          label: "Sync PDV hors ligne",
          body: "Preservez la continuite agence avec identite appareil, files, replay et revue conflits.",
          metric: "Replay",
        },
        controls: {
          label: "Controles tenant",
          body: "Forcez RBAC, step-up, maker-checker, gates modules et acces auditables.",
          metric: "RBAC",
        },
      },
      statusCards: {
        uptime: "Portee tenant",
        audit: "Preuve source",
        sync: "Replay hors ligne",
      },
      capabilityCards: {
        inventory: "Preuve inventaire",
        security: "Securite par role",
        insight: "Vue cloture",
      },
    },
    layout: {
      login: {
        eyebrow: "Acces protege",
        title: "Connectez-vous a l'espace operationnel",
        body: "Accedez a l'espace tenant ou stock, caisse, cloture, rapprochement, paie et controles partagent une piste de preuves.",
      },
      register: {
        eyebrow: "Demarrage espace OHADA",
        title: "Creez le tenant qui pilotera vos operations",
        body: "Configurez organisation, contexte pays, compte administrateur et espace pret modules avant d'inviter les equipes.",
      },
      forgot: {
        eyebrow: "Recuperation compte",
        title: "Recuperez l'acces en securite",
        body: "Reinitialisez vos identifiants avec les memes protections que la plateforme StockFlow.",
      },
      verify: {
        eyebrow: "Verification",
        title: "Confirmez votre compte",
        body: "Terminez la verification et entrez dans un espace operationnel protege.",
      },
    },
    login: {
      badge: "Connexion tenant",
      title: "Accedez a votre espace operationnel",
      subtitle: "Revoyez le PDV, stock, finance, cloture, paie et controles du jour depuis une session portee tenant.",
      email: "Adresse email",
      emailPlaceholder: "vous@entreprise.com",
      password: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      remember: "Se souvenir de moi",
      forgot: "Mot de passe oublie ?",
      submit: "Connexion securisee",
      loading: "Connexion",
      newHere: "Nouveau sur AqStoqFlow ?",
      createAccount: "Creer un compte",
      secureNote: "Les sessions sont portees tenant et permission-aware parce que l'espace touche cash, stock, paie, fournisseurs, conformite et cloture.",
      methodTitle: "Acces email et mot de passe",
      methodSubtitle: "Utilisez le flux mot de passe porte tenant. Les modules proteges peuvent redemander une verification recente.",
      sso: "SSO organisation",
      ssoHint: "Domaine route",
      passkey: "Cle d'acces",
      passkeyHint: "Appareil verifie",
      passwordMethod: "Mot de passe",
      passwordHint: "Acces standard",
      unavailableTitle: "Methode non activee",
      unavailableBody: "Cet espace utilise actuellement l'authentification par email et mot de passe.",
      unavailableHint: "Continuez avec le formulaire ci-dessous.",
      divider: "ou continuer avec le mot de passe",
      accessLevel: "Console tenant",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      registeredTitle: "Verifiez votre email",
      registeredBody: "Votre espace tenant a ete cree. Verifiez votre email avant de vous connecter.",
      errors: {
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caracteres",
        authFailed: "Echec d'authentification",
        verifyTitle: "Verification requise",
        verifyBody: "Veuillez verifier votre adresse email avant d'acceder au tableau de bord.",
        verifyHint: "Utilisez le code envoye dans votre boite email, puis reconnectez-vous.",
        unexpectedTitle: "Erreur inattendue",
        unexpectedBody: "Une erreur inattendue est survenue pendant la connexion",
        tryAgain: "Veuillez reessayer",
        attempt: "Tentative",
        connectionTitle: "Erreur de connexion",
        connectionBody: "Impossible de joindre le service d'authentification. Veuillez reessayer.",
        connectionHint: "Erreur reseau ou serveur",
      },
      successTitle: "Connexion validee",
      successBody: "Acces espace verifie.",
    },
    register: {
      badge: "Creer espace tenant",
      title: "Preparez un espace operationnel OHADA",
      subtitle: "Capturez le contexte organisation utilise par les modules, packs pays, controles agence et acces administrateur.",
      step: "Etape",
      of: "sur",
      steps: {
        personal: "Gerant",
        company: "Tenant",
        security: "Acces",
      },
      fields: {
        firstName: "Prenom",
        firstNamePlaceholder: "Jeanne",
        lastName: "Nom",
        lastNamePlaceholder: "Doe",
        email: "Email professionnel",
        emailPlaceholder: "jeanne@entreprise.com",
        phone: "Telephone",
        phonePlaceholder: "+237 6 00 00 00 00",
        companyName: "Nom de l'entreprise",
        companyNamePlaceholder: "AqStoq Retail Group",
        companySize: "Taille de l'entreprise",
        selectCompanySize: "Selectionner la taille",
        industry: "Secteur",
        selectIndustry: "Selectionner le secteur",
        country: "Pays",
        countryPlaceholder: "Cameroun",
        state: "Region ou province",
        statePlaceholder: "Centre",
        address: "Adresse professionnelle",
        addressPlaceholder: "Rue, ville, code postal",
        currency: "Devise par defaut",
        timezone: "Fuseau horaire",
        defaultLocale: "Langue de l'espace",
        password: "Mot de passe",
        passwordPlaceholder: "Creez un mot de passe solide",
        confirmPassword: "Confirmer le mot de passe",
        confirmPasswordPlaceholder: "Confirmez le mot de passe",
        termsPrefix: "J'accepte les",
        terms: "Conditions d'utilisation",
        and: "et la",
        privacy: "Politique de confidentialite",
      },
      companySizes: {
        small: "1-10 employes",
        medium: "11-50 employes",
        large: "51-200 employes",
        enterprise: "201+ employes",
      },
      infoBox:
        "AqStoqFlow cree votre organisation, prepare l'acces administrateur et un espace porte tenant.",
      passwordStrength: "Force du mot de passe",
      passwordLevels: {
        developing: "En progression",
        strong: "Solide",
        excellent: "Excellent",
      },
      continue: "Continuer",
      back: "Retour",
      create: "Creer le compte",
      creating: "Creation",
      already: "Vous avez deja un compte ?",
      signIn: "Se connecter",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      warningTitle: "Completez cette etape",
      warningBody: "Veuillez remplir les champs requis avant de continuer.",
      successTitle: "Compte cree",
      successBody: "Veuillez verifier votre email avant de vous connecter.",
      errorTitle: "Echec d'inscription",
      errorHint: "Verifiez vos informations puis reessayez.",
      networkTitle: "Erreur reseau",
      networkBody: "Impossible de creer le compte. Veuillez reessayer.",
      networkHint: "Inscription echouee",
      blueprintTitle: "Plan espace operationnel",
      blueprintBody: "AqStoqFlow prepare portee tenant, gates modules et valeurs pretes preuves pendant la configuration.",
      setupTime: "Setup guide",
      setupTrust: "Securite admin tenant",
      blueprintItems: {
        organization: "Organisation tenant creee",
        admin: "Acces administrateur prepare",
        inventory: "PDV, stock, AP et controles prepares",
      },
      errors: {
        firstNameRequired: "Le prenom est requis",
        firstNameMin: "Le prenom doit contenir au moins 2 caracteres",
        lastNameRequired: "Le nom est requis",
        lastNameMin: "Le nom doit contenir au moins 2 caracteres",
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        phoneRequired: "Le telephone est requis",
        companyRequired: "Le nom de l'entreprise est requis",
        companyMin: "Le nom de l'entreprise doit contenir au moins 2 caracteres",
        companySizeRequired: "La taille de l'entreprise est requise",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caracteres",
        confirmRequired: "Veuillez confirmer votre mot de passe",
        confirmMismatch: "Les mots de passe ne correspondent pas",
        termsRequired: "Vous devez accepter les conditions",
      },
    },
  },
} as const;
