export type AuthLocale = "en" | "fr";

export function getAuthLocale(pathname: string): AuthLocale {
  return pathname.match(/^\/fr(?:\/|$)/) ? "fr" : "en";
}

export const authCopy = {
  en: {
    common: {
      brandSubtitle: "OHADA operating system",
      languageAria: "Switch language",
      switchToLight: "Switch to light theme",
      switchToDark: "Switch to dark theme",
      light: "Light",
      dark: "Dark",
      encrypted: "Organization-scoped session",
      teamReady: "Controlled module access",
      permissionAware: "Role access, verification, audit",
      processing: "Processing...",
      liveAccess: "Protected OHADA workspace",
      workspaceSignal: "Evidence-led session",
      trustTitle: "Access protects the operating record",
      trustBody:
        "Every sign-in can touch stock, cash, payroll, supplier payments, compliance evidence, and close work, so organization scope, assigned access, and audit history remain visible.",
      commandTitle: "Secure workspace entry",
      commandBody: "One guarded entry point for operators, accountants, payroll teams, managers, and organization administrators.",
      moduleShowcaseTitle: "What this session can unlock",
      moduleShowcaseBody:
        "POS, inventory, purchasing/AP, payments, reconciliation, accounting close, compliance, payroll, offline sync, and controls are reached from the same protected workspace.",
      moduleHighlights: {
        pos: {
          label: "POS, receipts, and cash",
          body: "Open cashier sessions, sell, issue receipts, manage returns, and preserve payment evidence.",
          metric: "Checkout",
        },
        inventory: {
          label: "Stock truth by location",
          body: "Track items, counts, transfers, write-offs, valuation signals, and location-level stock.",
          metric: "Stock proof",
        },
        purchasing: {
          label: "Purchasing/AP controls",
          body: "Coordinate POs, receiving, supplier invoices, matching, approvals, and payment release.",
          metric: "AP flow",
        },
        accounting: {
          label: "OHADA close assurance",
          body: "Keep chart, journals, posting rules, trial balance, source links, and proof packs aligned.",
          metric: "Close",
        },
        compliance: {
          label: "Compliance country packs",
          body: "Govern fiscal documents, legal evidence, authority queues, and country-pack rules.",
          metric: "Rules",
        },
        reconciliation: {
          label: "Payment reconciliation",
          body: "Match provider evidence and statements, resolve suspense, and protect payment truth before close.",
          metric: "Suspense",
        },
        payroll: {
          label: "Payroll and declarations",
          body: "Connect employees, contracts, attendance, leave, payroll runs, approvals, and postings.",
          metric: "People",
        },
        offline: {
          label: "Offline POS sync",
          body: "Preserve branch continuity with device identity, queued work, replay, and conflict review.",
          metric: "Replay",
        },
        controls: {
          label: "Roles and maker-checker",
          body: "Enforce role access, fresh verification, maker-checker review, controlled module access, and audit history.",
          metric: "Access",
        },
      },
      statusCards: {
        uptime: "Organization scope",
        audit: "Source evidence",
        sync: "Offline replay",
      },
      capabilityCards: {
        inventory: "Inventory evidence",
        security: "Role security",
        insight: "Close insight",
      },
    },
    layout: {
      login: {
        eyebrow: "Secure workspace access",
        title: "Return to your controlled OHADA workspace",
        body: "Continue where sales, stock, payments, payroll, close, and compliance evidence remain connected to the right organization and role.",
        journeyCards: {
          label: "Access checks",
          context: {
            title: "Organization context",
            body: "Open the correct company and branch scope.",
          },
          access: {
            title: "Role-aware entry",
            body: "Available work follows assigned permissions.",
          },
          assurance: {
            title: "Fresh verification",
            body: "Sensitive actions can request a recent check.",
          },
        },
      },
      register: {
        eyebrow: "OHADA workspace setup",
        title: "Set up the operating workspace around the business",
        body: "Define company identity, country context, administrator access, and the initial control baseline before inviting teams.",
        journeyCards: {
          label: "Workspace setup",
          context: {
            title: "Company context",
            body: "Define organization, country, currency, and language.",
          },
          access: {
            title: "Administrator boundary",
            body: "Create the first controlled access role.",
          },
          assurance: {
            title: "Rollout baseline",
            body: "Prepare module and evidence expectations.",
          },
        },
      },
      forgot: {
        eyebrow: "Account recovery",
        title: "Recover access securely",
        body: "Reset credentials with the same safeguards used across the Stoquify platform.",
      },
      verify: {
        eyebrow: "Verification",
        title: "Confirm your account",
        body: "Complete verification and step into a protected operational workspace.",
      },
    },
    login: {
      badge: "Secure workspace session",
      title: "Return to your operating workspace",
      subtitle: "Resume work across POS, stock, payments, payroll, reconciliation, close, and compliance according to your assigned access.",
      email: "Email address",
      emailPlaceholder: "you@company.com",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      remember: "Remember me",
      forgot: "Forgot password?",
      submit: "Enter workspace",
      loading: "Signing in",
      newHere: "New to Stoquify?",
      createAccount: "Create an account",
      secureNote: "Signing in opens a workspace that can affect cash, stock, payroll, suppliers, compliance, payments, and close evidence.",
      methodTitle: "Workspace email access",
      methodSubtitle: "Use your organization email and password. Sensitive actions can still request fresh verification when needed.",
      sso: "Organization SSO",
      ssoHint: "Domain routed",
      passkey: "Passkey",
      passkeyHint: "Device verified",
      passwordMethod: "Password",
      passwordHint: "Standard access",
      unavailableTitle: "Method Not Enabled",
      unavailableBody: "This workspace is currently using email and password authentication.",
      unavailableHint: "Continue with the password form below.",
      divider: "or continue with password",
      accessLevel: "Organization console",
      showPassword: "Show password",
      hidePassword: "Hide password",
      registeredTitle: "Check Your Email",
      registeredBody: "Your organization workspace was created. Verify your email before signing in.",
      errors: {
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        authFailed: "Authentication Failed",
        verifyTitle: "Verification Required",
        verifyBody: "Please verify your email address before accessing the dashboard.",
        verifyHint: "Use the code sent to your inbox, then sign in again.",
        unexpectedTitle: "Unexpected Error",
        unexpectedBody: "An unexpected error occurred during login",
        tryAgain: "Please try again",
        attempt: "Attempt",
        connectionTitle: "Connection Error",
        connectionBody: "Unable to connect to authentication service. Please try again.",
        connectionHint: "Network or server error",
      },
      successTitle: "Signed in",
      successBody: "Workspace access verified.",
    },
    register: {
      badge: "Create OHADA workspace",
      title: "Build the operating workspace",
      subtitle: "Capture the company context used for modules, country packs, payments, branch controls, and administrator access.",
      step: "Step",
      of: "of",
      steps: {
        personal: "Operator",
        company: "Organization",
        security: "Security",
      },
      fields: {
        firstName: "First name",
        firstNamePlaceholder: "Jane",
        lastName: "Last name",
        lastNamePlaceholder: "Doe",
        email: "Work email",
        emailPlaceholder: "jane@company.com",
        phone: "Phone number",
        phonePlaceholder: "+1 555 0100",
        companyName: "Company name",
        companyNamePlaceholder: "AqStoq Retail Group",
        companySize: "Company size",
        selectCompanySize: "Select company size",
        industry: "Industry",
        selectIndustry: "Select industry",
        country: "Country",
        countryPlaceholder: "Cameroon",
        state: "State or province",
        statePlaceholder: "Centre",
        address: "Business address",
        addressPlaceholder: "Street, city, postal code",
        currency: "Default currency",
        timezone: "Timezone",
        defaultLocale: "Workspace language",
        password: "Password",
        passwordPlaceholder: "Create a strong password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Confirm password",
        termsPrefix: "I agree to the",
        terms: "Terms of Service",
        and: "and",
        privacy: "Privacy Policy",
      },
      companySizes: {
        small: "1-10 employees",
        medium: "11-50 employees",
        large: "51-200 employees",
        enterprise: "201+ employees",
      },
      infoBox:
        "Stoquify creates your organization, assigns administrator access, and prepares the initial workspace context.",
      passwordStrength: "Password strength",
      passwordLevels: {
        developing: "Developing",
        strong: "Strong",
        excellent: "Excellent",
      },
      continue: "Continue",
      back: "Back",
      create: "Create account",
      creating: "Creating",
      already: "Already have an account?",
      signIn: "Sign in",
      showPassword: "Show password",
      hidePassword: "Hide password",
      warningTitle: "Complete This Step",
      warningBody: "Please fill in the required fields before continuing.",
      successTitle: "Account Created",
      successBody: "Please check your email to verify your account before signing in.",
      errorTitle: "Registration Failed",
      errorHint: "Please check your information and try again.",
      networkTitle: "Network Error",
      networkBody: "Unable to create account. Please try again.",
      networkHint: "Registration failed",
      blueprintTitle: "Workspace control blueprint",
      blueprintBody: "Stoquify prepares organization scope, country settings, controlled module access, and evidence expectations while you complete setup.",
      setupTime: "Guided setup",
      setupTrust: "Administrator security",
      blueprintItems: {
        organization: "Organization context created",
        admin: "Administrator access prepared",
        inventory: "POS, stock, payments, payroll, and controls prepared",
      },
      errors: {
        firstNameRequired: "First name is required",
        firstNameMin: "First name must be at least 2 characters",
        lastNameRequired: "Last name is required",
        lastNameMin: "Last name must be at least 2 characters",
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        phoneRequired: "Phone number is required",
        companyRequired: "Company name is required",
        companyMin: "Company name must be at least 2 characters",
        companySizeRequired: "Company size is required",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        confirmRequired: "Please confirm your password",
        confirmMismatch: "Passwords do not match",
        termsRequired: "You must accept the terms and conditions",
      },
    },
  },
  fr: {
    common: {
      brandSubtitle: "Système opérationnel OHADA",
      languageAria: "Changer de langue",
      switchToLight: "Passer au thème clair",
      switchToDark: "Passer au thème sombre",
      light: "Clair",
      dark: "Sombre",
      encrypted: "Session limitée à l'organisation",
      teamReady: "Accès aux modules contrôlé",
      permissionAware: "Rôles, vérification, audit",
      processing: "Traitement...",
      liveAccess: "Espace OHADA protégé",
      workspaceSignal: "Session guidée par les preuves",
      trustTitle: "L'accès protège le dossier opérationnel",
      trustBody:
        "Chaque connexion peut toucher les stocks, la trésorerie, la paie, les paiements fournisseurs, la conformité et la clôture ; le périmètre d'organisation, les autorisations et l'historique restent donc visibles.",
      commandTitle: "Entrée sécurisée dans l'espace",
      commandBody: "Un point d'entrée protégé pour les opérateurs, comptables, équipes de paie, responsables et administrateurs de l'organisation.",
      moduleShowcaseTitle: "Ce que cette session peut ouvrir",
      moduleShowcaseBody:
        "Point de vente, inventaire, achats et dettes, paiements, rapprochement, clôture, conformité, paie, synchronisation hors ligne et contrôles sont accessibles depuis le même espace protégé.",
      moduleHighlights: {
        pos: {
          label: "PDV, reçus et caisse",
          body: "Ouvrez les sessions de caisse, ventes, reçus, retours et preuves de paiement.",
          metric: "Caisse",
        },
        inventory: {
          label: "Vérité stock par lieu",
          body: "Suivez les articles, comptages, transferts, sorties, valorisation et stock par site.",
          metric: "Preuve stock",
        },
        purchasing: {
          label: "Contrôle achats et dettes",
          body: "Coordonnez les bons de commande, réceptions, factures fournisseur, rapprochement, validations et libération paiement.",
          metric: "Dettes",
        },
        accounting: {
          label: "Assurance clôture OHADA",
          body: "Gardez plan, journaux, règles d'écriture, balance, sources et dossiers de preuves alignés.",
          metric: "Clôture",
        },
        compliance: {
          label: "Packs pays conformité",
          body: "Gouvernez documents fiscaux, preuves légales, files des autorités et règles pays.",
          metric: "Règles",
        },
        reconciliation: {
          label: "Rapprochement paiements",
          body: "Rapprochez les preuves des prestataires et relevés, résolvez suspenses et protégez la vérité paiement avant clôture.",
          metric: "Suspense",
        },
        payroll: {
          label: "Paie et déclarations",
          body: "Reliez employés, contrats, présence, congés, cycles de paie, validations et écritures.",
          metric: "Équipe",
        },
        offline: {
          label: "Synchronisation PDV hors ligne",
          body: "Préservez la continuité agence avec identité appareil, files, rejeu et revue des conflits.",
          metric: "Rejeu",
        },
        controls: {
          label: "Rôles et double validation",
          body: "Appliquez les rôles, la vérification récente, la double validation, le contrôle d'accès aux modules et l'historique d'audit.",
          metric: "Accès",
        },
      },
      statusCards: {
        uptime: "Périmètre organisation",
        audit: "Preuves sources",
        sync: "Rejeu hors ligne",
      },
      capabilityCards: {
        inventory: "Preuve inventaire",
        security: "Sécurité par rôle",
        insight: "Vue clôture",
      },
    },
    layout: {
      login: {
        eyebrow: "Accès sécurisé",
        title: "Retrouvez votre espace OHADA sous contrôle",
        body: "Reprenez le travail là où ventes, stocks, paiements, paie, clôture et conformité restent reliés à la bonne organisation et au bon rôle.",
        journeyCards: {
          label: "Contrôles d'accès",
          context: {
            title: "Contexte d'organisation",
            body: "Ouvrez le bon périmètre d'entreprise et d'agence.",
          },
          access: {
            title: "Accès selon le rôle",
            body: "Les fonctions disponibles suivent vos autorisations.",
          },
          assurance: {
            title: "Vérification récente",
            body: "Les actions sensibles peuvent exiger un nouveau contrôle.",
          },
        },
      },
      register: {
        eyebrow: "Configuration de l'espace OHADA",
        title: "Configurez l'espace opérationnel autour de l'entreprise",
        body: "Définissez l'identité de l'entreprise, le contexte pays, l'accès administrateur et le socle de contrôle avant d'inviter les équipes.",
        journeyCards: {
          label: "Configuration de l'espace",
          context: {
            title: "Contexte d'entreprise",
            body: "Définissez l'organisation, pays, devise et langue.",
          },
          access: {
            title: "Périmètre administrateur",
            body: "Créez le premier rôle avec un accès contrôlé.",
          },
          assurance: {
            title: "Socle de déploiement",
            body: "Préparez les attentes de modules et de preuves.",
          },
        },
      },
      forgot: {
        eyebrow: "Récupération compte",
        title: "Récupérez l'accès en sécurité",
        body: "Réinitialisez vos identifiants avec les mêmes protections que la plateforme Stoquify.",
      },
      verify: {
        eyebrow: "Vérification",
        title: "Confirmez votre compte",
        body: "Terminez la vérification et entrez dans un espace opérationnel protégé.",
      },
    },
    login: {
      badge: "Session d'espace sécurisée",
      title: "Retrouvez votre espace opérationnel",
      subtitle: "Reprenez le travail sur le point de vente, les stocks, les paiements, la paie, le rapprochement, la clôture et la conformité selon vos autorisations.",
      email: "Adresse email",
      emailPlaceholder: "vous@entreprise.com",
      password: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      remember: "Se souvenir de moi",
      forgot: "Mot de passe oublié ?",
      submit: "Entrer dans l'espace",
      loading: "Connexion",
      newHere: "Nouveau sur Stoquify ?",
      createAccount: "Créer un compte",
      secureNote: "La connexion ouvre un espace qui peut toucher trésorerie, stock, paie, fournisseurs, conformité, paiements et preuves de clôture.",
      methodTitle: "Accès par email professionnel",
      methodSubtitle: "Utilisez l'email et le mot de passe de votre organisation. Les actions sensibles peuvent encore exiger une vérification récente.",
      sso: "SSO organisation",
      ssoHint: "Domaine géré",
      passkey: "Clé d'accès",
      passkeyHint: "Appareil vérifié",
      passwordMethod: "Mot de passe",
      passwordHint: "Accès standard",
      unavailableTitle: "Méthode non activée",
      unavailableBody: "Cet espace utilise actuellement l'authentification par email et mot de passe.",
      unavailableHint: "Continuez avec le formulaire ci-dessous.",
      divider: "ou continuer avec le mot de passe",
      accessLevel: "Console de l'organisation",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      registeredTitle: "Vérifiez votre email",
      registeredBody: "Votre espace d'organisation a été créé. Vérifiez votre email avant de vous connecter.",
      errors: {
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caractères",
        authFailed: "Échec d'authentification",
        verifyTitle: "Vérification requise",
        verifyBody: "Veuillez vérifier votre adresse email avant d'accéder au tableau de bord.",
        verifyHint: "Utilisez le code envoyé dans votre boîte email, puis reconnectez-vous.",
        unexpectedTitle: "Erreur inattendue",
        unexpectedBody: "Une erreur inattendue est survenue pendant la connexion",
        tryAgain: "Veuillez réessayer",
        attempt: "Tentative",
        connectionTitle: "Erreur de connexion",
        connectionBody: "Impossible de joindre le service d'authentification. Veuillez réessayer.",
        connectionHint: "Erreur réseau ou serveur",
      },
      successTitle: "Connexion validée",
      successBody: "Accès à l'espace vérifié.",
    },
    register: {
      badge: "Créer espace OHADA",
      title: "Construisez l'espace opérationnel",
      subtitle: "Définissez le contexte d'entreprise utilisé par les modules, les règles pays, les paiements, les agences et l'accès administrateur.",
      step: "Étape",
      of: "sur",
      steps: {
        personal: "Opérateur",
        company: "Organisation",
        security: "Sécurité",
      },
      fields: {
        firstName: "Prénom",
        firstNamePlaceholder: "Jeanne",
        lastName: "Nom",
        lastNamePlaceholder: "Doe",
        email: "Email professionnel",
        emailPlaceholder: "jeanne@entreprise.com",
        phone: "Téléphone",
        phonePlaceholder: "+237 6 00 00 00 00",
        companyName: "Nom de l'entreprise",
        companyNamePlaceholder: "AqStoq Retail Group",
        companySize: "Taille de l'entreprise",
        selectCompanySize: "Sélectionner la taille",
        industry: "Secteur",
        selectIndustry: "Sélectionner le secteur",
        country: "Pays",
        countryPlaceholder: "Cameroun",
        state: "Région ou province",
        statePlaceholder: "Centre",
        address: "Adresse professionnelle",
        addressPlaceholder: "Rue, ville, code postal",
        currency: "Devise par défaut",
        timezone: "Fuseau horaire",
        defaultLocale: "Langue de l'espace",
        password: "Mot de passe",
        passwordPlaceholder: "Créez un mot de passe solide",
        confirmPassword: "Confirmer le mot de passe",
        confirmPasswordPlaceholder: "Confirmez le mot de passe",
        termsPrefix: "J'accepte les",
        terms: "Conditions d'utilisation",
        and: "et la",
        privacy: "Politique de confidentialité",
      },
      companySizes: {
        small: "1-10 employés",
        medium: "11-50 employés",
        large: "51-200 employés",
        enterprise: "201+ employés",
      },
      infoBox:
        "Stoquify crée votre organisation, attribue l'accès administrateur et prépare le contexte initial de l'espace.",
      passwordStrength: "Force du mot de passe",
      passwordLevels: {
        developing: "En progression",
        strong: "Solide",
        excellent: "Excellent",
      },
      continue: "Continuer",
      back: "Retour",
      create: "Créer le compte",
      creating: "Création",
      already: "Vous avez déjà un compte ?",
      signIn: "Se connecter",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      warningTitle: "Complétez cette étape",
      warningBody: "Veuillez remplir les champs requis avant de continuer.",
      successTitle: "Compte créé",
      successBody: "Veuillez vérifier votre email avant de vous connecter.",
      errorTitle: "Échec d'inscription",
      errorHint: "Vérifiez vos informations puis réessayez.",
      networkTitle: "Erreur réseau",
      networkBody: "Impossible de créer le compte. Veuillez réessayer.",
      networkHint: "Inscription échouée",
      blueprintTitle: "Plan de contrôle de l'espace",
      blueprintBody: "Stoquify prépare le périmètre de l'organisation, les réglages pays, le contrôle d'accès aux modules et les attentes de preuves.",
      setupTime: "Configuration guidée",
      setupTrust: "Sécurité administrateur",
      blueprintItems: {
        organization: "Contexte d'organisation créé",
        admin: "Accès administrateur préparé",
        inventory: "PDV, stock, paiements, paie et contrôles préparés",
      },
      errors: {
        firstNameRequired: "Le prénom est requis",
        firstNameMin: "Le prénom doit contenir au moins 2 caractères",
        lastNameRequired: "Le nom est requis",
        lastNameMin: "Le nom doit contenir au moins 2 caractères",
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        phoneRequired: "Le téléphone est requis",
        companyRequired: "Le nom de l'entreprise est requis",
        companyMin: "Le nom de l'entreprise doit contenir au moins 2 caractères",
        companySizeRequired: "La taille de l'entreprise est requise",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caractères",
        confirmRequired: "Veuillez confirmer votre mot de passe",
        confirmMismatch: "Les mots de passe ne correspondent pas",
        termsRequired: "Vous devez accepter les conditions",
      },
    },
  },
} as const;
