export type AuthLocale = "en" | "fr";

export function getAuthLocale(pathname: string): AuthLocale {
  return pathname.match(/^\/fr(?:\/|$)/) ? "fr" : "en";
}

export const authCopy = {
  en: {
    common: {
      brandSubtitle: "Enterprise OS",
      languageAria: "Switch language",
      switchToLight: "Switch to light theme",
      switchToDark: "Switch to dark theme",
      light: "Light",
      dark: "Dark",
      encrypted: "Encrypted access",
      teamReady: "Team ready",
      permissionAware: "Permission aware",
      processing: "Processing...",
      liveAccess: "Live access perimeter",
      workspaceSignal: "Workspace signal",
      trustTitle: "Designed for daily operators",
      trustBody:
        "Fast access, clear controls, secure roles, and bilingual workflows for teams that run stock every day.",
      commandTitle: "Access cockpit",
      commandBody: "A guarded entry point for operators, managers, finance teams, and administrators.",
      moduleShowcaseTitle: "Business modules",
      moduleShowcaseBody:
        "Inventory, accounting, sales, purchasing, and reporting are ready from the same protected workspace.",
      moduleHighlights: {
        inventory: {
          label: "Inventory control",
          body: "Track stock levels, locations, transfers, categories, brands, and units with live accuracy.",
          metric: "Stock live",
        },
        accounting: {
          label: "Accounting & finance",
          body: "Follow payments, cash drawers, tax controls, receipts, and daily financial visibility.",
          metric: "Finance ready",
        },
        pos: {
          label: "POS sales",
          body: "Run checkout workflows, customer sales, receipt handling, and session-aware operations.",
          metric: "Checkout",
        },
        purchasing: {
          label: "Purchasing",
          body: "Coordinate suppliers, purchase orders, deliveries, costs, and replenishment decisions.",
          metric: "Supply flow",
        },
        reporting: {
          label: "Reports & insight",
          body: "Monitor performance, stock value, sales trends, and operational signals in real time.",
          metric: "Live insight",
        },
      },
      statusCards: {
        uptime: "Session uptime",
        audit: "Audit trail",
        sync: "Live sync",
      },
      capabilityCards: {
        inventory: "Inventory accuracy",
        security: "Role security",
        insight: "Live insight",
      },
    },
    layout: {
      login: {
        eyebrow: "Secure access",
        title: "Welcome back to StockFlow",
        body: "Operate inventory, sales, purchasing, and finance from one calm enterprise command center.",
      },
      register: {
        eyebrow: "Business onboarding",
        title: "Launch your retail operating system",
        body: "Set up your organization, invite your team, and start managing stock with confidence.",
      },
      forgot: {
        eyebrow: "Account recovery",
        title: "Recover access securely",
        body: "Reset credentials with the same safeguards used across the StockFlow platform.",
      },
      verify: {
        eyebrow: "Verification",
        title: "Confirm your account",
        body: "Complete verification and step into a protected operational workspace.",
      },
    },
    login: {
      badge: "Operator sign in",
      title: "Access your workspace",
      subtitle: "Sign in to manage inventory, purchasing, sales, finance, and team permissions.",
      email: "Email address",
      emailPlaceholder: "you@company.com",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      remember: "Remember me",
      forgot: "Forgot password?",
      submit: "Sign in securely",
      loading: "Signing in",
      newHere: "New to StockFlow?",
      createAccount: "Create an account",
      secureNote: "Sessions are protected by organization roles and permission-aware dashboard access.",
      methodTitle: "Preferred access",
      methodSubtitle: "Start with enterprise-grade options, or continue with password access.",
      sso: "Organization SSO",
      ssoHint: "Domain routed",
      passkey: "Passkey",
      passkeyHint: "Device verified",
      passwordMethod: "Password",
      passwordHint: "Standard access",
      unavailableTitle: "Method Not Enabled",
      unavailableBody: "This workspace is currently using email and password authentication.",
      unavailableHint: "Continue with the password form below.",
      divider: "or continue with password",
      accessLevel: "Operator console",
      showPassword: "Show password",
      hidePassword: "Hide password",
      registeredTitle: "Check Your Email",
      registeredBody: "Your workspace was created. Verify your email before signing in.",
      errors: {
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        authFailed: "Authentication Failed",
        verifyTitle: "Verification Required",
        verifyBody: "Please verify your email address before accessing the dashboard.",
        verifyHint: "Use the code sent to your inbox, then sign in again.",
        unexpectedTitle: "Unexpected Error",
        unexpectedBody: "An unexpected error occurred during login",
        tryAgain: "Please try again",
        attempt: "Attempt",
        connectionTitle: "Connection Error",
        connectionBody: "Unable to connect to authentication service. Please try again.",
        connectionHint: "Network or server error",
      },
      successTitle: "Login Successful",
      successBody: "Welcome back!",
    },
    register: {
      badge: "Create workspace",
      title: "Start with a guided setup",
      subtitle: "Build your organization profile and secure the administrator account.",
      step: "Step",
      of: "of",
      steps: {
        personal: "Personal",
        company: "Company",
        security: "Security",
      },
      fields: {
        firstName: "First name",
        firstNamePlaceholder: "Jane",
        lastName: "Last name",
        lastNamePlaceholder: "Doe",
        email: "Work email",
        emailPlaceholder: "jane@company.com",
        phone: "Phone number",
        phonePlaceholder: "+1 555 0100",
        companyName: "Company name",
        companyNamePlaceholder: "Acme Retail Group",
        companySize: "Company size",
        selectCompanySize: "Select company size",
        industry: "Industry",
        selectIndustry: "Select industry",
        country: "Country",
        countryPlaceholder: "Cameroon",
        state: "State or province",
        statePlaceholder: "Centre",
        address: "Business address",
        addressPlaceholder: "Street, city, postal code",
        currency: "Default currency",
        timezone: "Timezone",
        defaultLocale: "Workspace language",
        password: "Password",
        passwordPlaceholder: "Create a strong password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Confirm password",
        termsPrefix: "I agree to the",
        terms: "Terms of Service",
        and: "and",
        privacy: "Privacy Policy",
      },
      companySizes: {
        small: "1-10 employees",
        medium: "11-50 employees",
        large: "51-200 employees",
        enterprise: "201+ employees",
      },
      infoBox:
        "StockFlow creates your organization, assigns an administrator role, and prepares a secure workspace.",
      passwordStrength: "Password strength",
      passwordLevels: {
        developing: "Developing",
        strong: "Strong",
        excellent: "Excellent",
      },
      continue: "Continue",
      back: "Back",
      create: "Create account",
      creating: "Creating",
      already: "Already have an account?",
      signIn: "Sign in",
      showPassword: "Show password",
      hidePassword: "Hide password",
      warningTitle: "Complete This Step",
      warningBody: "Please fill in the required fields before continuing.",
      successTitle: "Account Created",
      successBody: "Please check your email to verify your account before signing in.",
      errorTitle: "Registration Failed",
      errorHint: "Please check your information and try again.",
      networkTitle: "Network Error",
      networkBody: "Unable to create account. Please try again.",
      networkHint: "Registration failed",
      blueprintTitle: "Workspace blueprint",
      blueprintBody: "StockFlow prepares the essentials while you complete the setup.",
      setupTime: "3 minute setup",
      setupTrust: "Admin-first security",
      blueprintItems: {
        organization: "Organization created",
        admin: "Administrator role assigned",
        inventory: "Inventory workspace prepared",
      },
      errors: {
        firstNameRequired: "First name is required",
        firstNameMin: "First name must be at least 2 characters",
        lastNameRequired: "Last name is required",
        lastNameMin: "Last name must be at least 2 characters",
        emailRequired: "Email is required",
        emailInvalid: "Please enter a valid email address",
        phoneRequired: "Phone number is required",
        companyRequired: "Company name is required",
        companyMin: "Company name must be at least 2 characters",
        companySizeRequired: "Company size is required",
        passwordRequired: "Password is required",
        passwordMin: "Password must be at least 12 characters",
        confirmRequired: "Please confirm your password",
        confirmMismatch: "Passwords do not match",
        termsRequired: "You must accept the terms and conditions",
      },
    },
  },
  fr: {
    common: {
      brandSubtitle: "Systeme entreprise",
      languageAria: "Changer de langue",
      switchToLight: "Passer au theme clair",
      switchToDark: "Passer au theme sombre",
      light: "Clair",
      dark: "Sombre",
      encrypted: "Acces chiffre",
      teamReady: "Pret equipe",
      permissionAware: "Permissions actives",
      processing: "Traitement...",
      liveAccess: "Perimetre d'acces actif",
      workspaceSignal: "Signal espace",
      trustTitle: "Concu pour les operateurs quotidiens",
      trustBody:
        "Acces rapide, controles clairs, roles securises et flux bilingues pour les equipes qui gerent le stock chaque jour.",
      commandTitle: "Cockpit d'acces",
      commandBody: "Un point d'entree protege pour operateurs, managers, finance et administrateurs.",
      moduleShowcaseTitle: "Modules metier",
      moduleShowcaseBody:
        "Inventaire, comptabilite, ventes, achats et rapports sont reunis dans le meme espace protege.",
      moduleHighlights: {
        inventory: {
          label: "Controle inventaire",
          body: "Suivez stocks, sites, transferts, categories, marques et unites avec precision en temps reel.",
          metric: "Stock actif",
        },
        accounting: {
          label: "Comptabilite & finance",
          body: "Suivez paiements, caisses, taxes, recus et visibilite financiere quotidienne.",
          metric: "Finance prete",
        },
        pos: {
          label: "Ventes POS",
          body: "Gerez encaissement, ventes clients, recus et operations liees aux sessions.",
          metric: "Caisse",
        },
        purchasing: {
          label: "Achats",
          body: "Coordonnez fournisseurs, commandes, livraisons, couts et decisions de reapprovisionnement.",
          metric: "Flux achat",
        },
        reporting: {
          label: "Rapports & vues",
          body: "Surveillez performance, valeur du stock, tendances de vente et signaux operationnels.",
          metric: "Vue live",
        },
      },
      statusCards: {
        uptime: "Disponibilite session",
        audit: "Journal audit",
        sync: "Sync active",
      },
      capabilityCards: {
        inventory: "Precision inventaire",
        security: "Securite par role",
        insight: "Vue temps reel",
      },
    },
    layout: {
      login: {
        eyebrow: "Acces securise",
        title: "Bon retour sur StockFlow",
        body: "Pilotez inventaire, ventes, achats et finance depuis un centre de commande enterprise calme.",
      },
      register: {
        eyebrow: "Demarrage entreprise",
        title: "Lancez votre systeme operationnel retail",
        body: "Configurez votre organisation, invitez votre equipe et commencez a gerer le stock avec confiance.",
      },
      forgot: {
        eyebrow: "Recuperation compte",
        title: "Recuperez l'acces en securite",
        body: "Reinitialisez vos identifiants avec les memes protections que la plateforme StockFlow.",
      },
      verify: {
        eyebrow: "Verification",
        title: "Confirmez votre compte",
        body: "Terminez la verification et entrez dans un espace operationnel protege.",
      },
    },
    login: {
      badge: "Connexion operateur",
      title: "Accedez a votre espace",
      subtitle: "Connectez-vous pour gerer inventaire, achats, ventes, finance et permissions equipe.",
      email: "Adresse email",
      emailPlaceholder: "vous@entreprise.com",
      password: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      remember: "Se souvenir de moi",
      forgot: "Mot de passe oublie ?",
      submit: "Connexion securisee",
      loading: "Connexion",
      newHere: "Nouveau sur StockFlow ?",
      createAccount: "Creer un compte",
      secureNote: "Les sessions sont protegees par les roles d'organisation et les permissions du tableau de bord.",
      methodTitle: "Acces prefere",
      methodSubtitle: "Commencez avec les options enterprise, ou continuez avec le mot de passe.",
      sso: "SSO organisation",
      ssoHint: "Domaine route",
      passkey: "Cle d'acces",
      passkeyHint: "Appareil verifie",
      passwordMethod: "Mot de passe",
      passwordHint: "Acces standard",
      unavailableTitle: "Methode non activee",
      unavailableBody: "Cet espace utilise actuellement l'authentification par email et mot de passe.",
      unavailableHint: "Continuez avec le formulaire ci-dessous.",
      divider: "ou continuer avec le mot de passe",
      accessLevel: "Console operateur",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      registeredTitle: "Verifiez votre email",
      registeredBody: "Votre espace a ete cree. Verifiez votre email avant de vous connecter.",
      errors: {
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caracteres",
        authFailed: "Echec d'authentification",
        verifyTitle: "Verification requise",
        verifyBody: "Veuillez verifier votre adresse email avant d'acceder au tableau de bord.",
        verifyHint: "Utilisez le code envoye dans votre boite email, puis reconnectez-vous.",
        unexpectedTitle: "Erreur inattendue",
        unexpectedBody: "Une erreur inattendue est survenue pendant la connexion",
        tryAgain: "Veuillez reessayer",
        attempt: "Tentative",
        connectionTitle: "Erreur de connexion",
        connectionBody: "Impossible de joindre le service d'authentification. Veuillez reessayer.",
        connectionHint: "Erreur reseau ou serveur",
      },
      successTitle: "Connexion reussie",
      successBody: "Bon retour !",
    },
    register: {
      badge: "Creer un espace",
      title: "Demarrez avec une configuration guidee",
      subtitle: "Creez le profil de votre organisation et securisez le compte administrateur.",
      step: "Etape",
      of: "sur",
      steps: {
        personal: "Personnel",
        company: "Entreprise",
        security: "Securite",
      },
      fields: {
        firstName: "Prenom",
        firstNamePlaceholder: "Jeanne",
        lastName: "Nom",
        lastNamePlaceholder: "Doe",
        email: "Email professionnel",
        emailPlaceholder: "jeanne@entreprise.com",
        phone: "Telephone",
        phonePlaceholder: "+237 6 00 00 00 00",
        companyName: "Nom de l'entreprise",
        companyNamePlaceholder: "Acme Retail Group",
        companySize: "Taille de l'entreprise",
        selectCompanySize: "Selectionner la taille",
        industry: "Secteur",
        selectIndustry: "Selectionner le secteur",
        country: "Pays",
        countryPlaceholder: "Cameroun",
        state: "Region ou province",
        statePlaceholder: "Centre",
        address: "Adresse professionnelle",
        addressPlaceholder: "Rue, ville, code postal",
        currency: "Devise par defaut",
        timezone: "Fuseau horaire",
        defaultLocale: "Langue de l'espace",
        password: "Mot de passe",
        passwordPlaceholder: "Creez un mot de passe solide",
        confirmPassword: "Confirmer le mot de passe",
        confirmPasswordPlaceholder: "Confirmez le mot de passe",
        termsPrefix: "J'accepte les",
        terms: "Conditions d'utilisation",
        and: "et la",
        privacy: "Politique de confidentialite",
      },
      companySizes: {
        small: "1-10 employes",
        medium: "11-50 employes",
        large: "51-200 employes",
        enterprise: "201+ employes",
      },
      infoBox:
        "StockFlow cree votre organisation, attribue un role administrateur et prepare un espace securise.",
      passwordStrength: "Force du mot de passe",
      passwordLevels: {
        developing: "En progression",
        strong: "Solide",
        excellent: "Excellent",
      },
      continue: "Continuer",
      back: "Retour",
      create: "Creer le compte",
      creating: "Creation",
      already: "Vous avez deja un compte ?",
      signIn: "Se connecter",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      warningTitle: "Completez cette etape",
      warningBody: "Veuillez remplir les champs requis avant de continuer.",
      successTitle: "Compte cree",
      successBody: "Veuillez verifier votre email avant de vous connecter.",
      errorTitle: "Echec d'inscription",
      errorHint: "Verifiez vos informations puis reessayez.",
      networkTitle: "Erreur reseau",
      networkBody: "Impossible de creer le compte. Veuillez reessayer.",
      networkHint: "Inscription echouee",
      blueprintTitle: "Plan de l'espace",
      blueprintBody: "StockFlow prepare les essentiels pendant que vous terminez la configuration.",
      setupTime: "Configuration 3 minutes",
      setupTrust: "Securite administrateur",
      blueprintItems: {
        organization: "Organisation creee",
        admin: "Role administrateur attribue",
        inventory: "Espace inventaire prepare",
      },
      errors: {
        firstNameRequired: "Le prenom est requis",
        firstNameMin: "Le prenom doit contenir au moins 2 caracteres",
        lastNameRequired: "Le nom est requis",
        lastNameMin: "Le nom doit contenir au moins 2 caracteres",
        emailRequired: "L'email est requis",
        emailInvalid: "Veuillez entrer une adresse email valide",
        phoneRequired: "Le telephone est requis",
        companyRequired: "Le nom de l'entreprise est requis",
        companyMin: "Le nom de l'entreprise doit contenir au moins 2 caracteres",
        companySizeRequired: "La taille de l'entreprise est requise",
        passwordRequired: "Le mot de passe est requis",
        passwordMin: "Le mot de passe doit contenir au moins 12 caracteres",
        confirmRequired: "Veuillez confirmer votre mot de passe",
        confirmMismatch: "Les mots de passe ne correspondent pas",
        termsRequired: "Vous devez accepter les conditions",
      },
    },
  },
} as const;
